from selenium.webdriver.common.by import By


class AccessValidationLocators:
    header_log = (By.CSS_SELECTOR,"div.nebula-action-bar__menu-container img[class ='nebula-image']")
    main_menu=(By.CSS_SELECTOR,"div[class='nebula-action-bar__menu-container'] button[aria-label='open menu']")
    pause_VideoButton=(By.CSS_SELECTOR,"div.nebula-hero__actions button span[class ='nebula-button__text']")
    video_card=(By.CSS_SELECTOR,"div.nebula-hero__call-to-action-container  a,.nebula-hero__video")
    loading_spinner=(By.CSS_SELECTOR,"div[id='nuxt-loading']")
    loading_bar = (By.CSS_SELECTOR, "html[class='nprogress-busy112']")
    loaded_screen=(By.CSS_SELECTOR,".atlas-app.index,.atlas-layout__content")
    card_title = (By.CSS_SELECTOR, "div[class='lesson-card__content'] div.lesson-card__metadata a p.nebula-card__title")
    get_started_button=(By.CSS_SELECTOR,"a[aria-label='button linking to educators page']")
    changeyourworld_withstemtext=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(3) div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    learnMoreButton = (By.CSS_SELECTOR,"button[class*='component-button-group__button--default']")
    junior_marshalTraining_text=(By.CSS_SELECTOR,"section[id='e6de5046-bf95-4d4b-9114-53613ec96944'] div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    animation_video =(By.CSS_SELECTOR,"section[id='c8cc0300-a737-4f12-ad4c-cfc189740e0a'] div.component-row__content div.component-hero__inner .component-hero__meta")
    fire_safety_text= (By.CSS_SELECTOR,"a[href*='76c8952d-5210-4016-9ce3-abcd4920d443'].nebula-card__title")
    play_button=(By.CSS_SELECTOR,"button[aria-label='Play']")
    educator_docbutton=(By.CSS_SELECTOR,"li[data-asset-id='e516f33d-5898-4fc7-99cc-0fa24fdbd709'] [href*='a954f238-6783-4a9c-bba4-974fbbf05598']")
    instructional_video =(By.CSS_SELECTOR,"section[id='7f59acaf-70d6-463b-9859-897c5556fb4f'] div.component-row__content div.component-hero__inner .component-hero__meta .component-text.component-hero__text .component-hero__title .nuxt-content")
    asset =(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(10) .component-row__content div[class*='nebula-card--asset--horizontal']")
    student_activity=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(12) div.component-row__content div.component-hero__inner .component-hero__meta .component-text.component-hero__text .component-hero__title .nuxt-content")
    activity_card=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(13) .lesson-card__metadata .nebula-card__title")
    Deputization_Resources=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(14) div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-feature-row__title .component-rich-text")
    quickLinks=(By.CSS_SELECTOR,"div.component-row__content nav.nebula-quicklinks.quicklinks a")
    nav_menu=(By.CSS_SELECTOR,"ul.nebula-tabs__list--widths-calculated li")
    online_safety_text=(By.CSS_SELECTOR,"section[id='4280e336-8d2e-4cbd-a434-c159d560bdbe'] div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    irresponsible_Behaviors_text=(By.CSS_SELECTOR,"section[id='ecfc84c6-0ab6-4fe4-8348-1989bffb252b'] div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    watch_now_button=(By.CSS_SELECTOR,"section[id='ecfc84c6-0ab6-4fe4-8348-1989bffb252b']  div.component-button-group__buttons a")
    our_mission=(By.CSS_SELECTOR,"section[id='8c98d6e0-52be-473d-888f-6697df605620'] div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    signup_for_immersive=(By.CSS_SELECTOR,"section[id='77896334-262a-4203-901a-1d348c04cfb4'] div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    behavior_oF_safedriving_text = (By.CSS_SELECTOR,"section[id='b63a0794-b174-46d9-97b0-711e090e8019'] div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    family_resources_text= (By.CSS_SELECTOR,"section[id='a671548a-1ea6-4af1-9697-941dbe5d80e6'] div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title")
    global_citizenaction_text = (By.CSS_SELECTOR,".component-text__title")
    mysterywriting_log=(By.CSS_SELECTOR,".component-feature-row__content")
    more_grades_lesson_headerText=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(4) div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title plain-text")
    main_header=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(1) div.component-row__content")
    claim_trial=(By.CSS_SELECTOR,"div.button-wrapper a.nebula-button[href*=free-registration], #button-group div.component-button-group__buttons a.nebula-button[href*='free-registration?campaign']")
    grade_text=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(2)  div[class='component-row__header component-row-header--unit-row'] .component-row__metadata div[class='component-rich-text']")
    mysterywriting_cardtitle=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(2) .component-row__content .unit-card__title")
    ready_mysterwriting_text=(By.CSS_SELECTOR,"div#__layout>div:nth-child(1)>div.page section:nth-child(6) div.component-row__content div.component-feature-row__content .component-feature-row__meta-wrap .component-feature-row__meta .component-text.component-feature-row__text .component-text__title plain-text")
    mystery_writing_header_img = (By.CSS_SELECTOR, "a[aria-label='Discovery Education Home']")
    genre_unit_header_text = (By.CSS_SELECTOR, "section[class*='component-unit-row']:nth-child(1)>div>div>div>div>div[class*='component-rich-text']>div>plain-text")
    narrative_unit_card_text = (By.CSS_SELECTOR, "section[class*='component-unit-row']:nth-child(1)>div[class='component-row__content']>div>div>div>a:nth-child(1)>div>div[class*='unit-card__meta']>div")
    informative_unit_card_text = (By.CSS_SELECTOR, "section[class*='component-unit-row']:nth-child(1)>div[class='component-row__content']>div>div>div>a:nth-child(2)>div>div[class*='unit-card__meta']>div")
    back_to_school_header_text = (By.CSS_SELECTOR, "section[class*='component-lesson-row']:nth-child(3)>div>div div[class*='component-rich-text']>div>plain-text")
    lesson_card_text = (By.CSS_SELECTOR, ".component-header__logo>a")
    back_to_school_lesson_card = (By.CSS_SELECTOR, "div#__layout>div:nth-child(1)>div.page section:nth-child(3) .component-row__content .lesson-card__link")
    profile_panel = (By.CSS_SELECTOR, "button[aria-label='Open Profile Panel']")
    help_center = (By.CSS_SELECTOR, "a[href*='https://help.'].atlas-button,.component-button-group__buttons a[href*='https://support.']")
    pricing = (By.CSS_SELECTOR, "a[href*='/pricing'].atlas-button,.component-button-group__buttons a[href*='https://support.']")
    building_essential_skills_text = (By.CSS_SELECTOR, ".atlas-layout__page>section:nth-child(2)>div:nth-child(1)>div>div>div>div>div>plain-text")
    building_essential_skills_unit_cards = (By.CSS_SELECTOR, "div#__layout>div:nth-child(1)>div.page section:nth-child(2) .component-row__content .unit-card__title")
    about_section_mystry_writing = (By.CSS_SELECTOR, ".component-subfooter__heading")
    introduce_genre_writing_text = (By.CSS_SELECTOR, ".atlas-layout__page>section:nth-child(4)>div:nth-child(1)>div>div>div>div>div>plain-text")
    introduce_genre_writing_unit_cards = (By.CSS_SELECTOR, "div#__layout>div:nth-child(1)>div.page section:nth-child(4) .component-row__content .unit-card__title")
    quick_writes_text = (By.CSS_SELECTOR, ".atlas-layout__page>section:nth-child(5)>div:nth-child(1)>div>div>div>div>div>plain-text")
    quick_writes_unit_cards = (By.CSS_SELECTOR, "div#__layout>div:nth-child(1)>div.page section:nth-child(5) .component-row__content .lesson-card__link")
    locked_text = (By.CSS_SELECTOR, ".atlas-layout__wrap-page>div>.atlas-lock__content>div>h1")
    ms_password = (By.CSS_SELECTOR, "#atlas-lock__code")
    submit = (By.CSS_SELECTOR, "button[aria-label='Submit']")
    sign_out_button = (By.CSS_SELECTOR, ".nebula-profile-panel__inner>ul>li>a[data-click-name='Sign Out']")
    mystery_science_header_img = (By.CSS_SELECTOR, ".component-header__home-logo>a")
    mystery_search_bar = (By.CSS_SELECTOR, ".nebula-product-bar__search-input")
    setting_writing_goals_text = (By.CSS_SELECTOR, ".component-lesson-embed__text>div:nth-child(2)>div>div>plain-text>strong")
    mystery_back_button = (By.CSS_SELECTOR, ".component-row__content>div>a, div.nebula-action-bar__button--back>a")
    essential_skills_text = (By.CSS_SELECTOR, ".component-hero__text>div>div>div>plain-text")
    informative_writing_text = (By.CSS_SELECTOR, ".component-hero__text>div>div>div>plain-text")
    quick_writes_unit_cards_text = (By.CSS_SELECTOR, ".component-text__subtitle >div>div>plain-text")
    atlas_search_field = (By.CSS_SELECTOR, ".asset-search__keyword .nebula-field-group .asset-search__keyword-inputs div[aria-label='Search'] button")
    atlas_recent_label = (By.CSS_SELECTOR, '.dashboard .nebula-button__text')
    atlas_app = (By.CSS_SELECTOR,".atlas-nav a[href*='https://atlas-apps']")
    apps_product_card_atlas = (By.CSS_SELECTOR, ".admin-card a[href*='apps']")
    atlas_app_list = (By.CSS_SELECTOR, '.product-card__label-title, .app-card__label-title')
    app_search = (By.CSS_SELECTOR, "input[aria-label ='search for component']")
    backToApp_button = (By.CSS_SELECTOR, ".editor-trigger .editor-trigger__end span:nth-child(1)")
    atlas_header = (By.CSS_SELECTOR, ".atlas-heading__title")
    first_app_card = (By.CSS_SELECTOR, "div.dashboard__products-grid .product-card__content .product-card__label-title a")
    atlas_app_card_edit_button = (By.CSS_SELECTOR, ".product-card__subactions .atlas-editor__button-wrap .nebula-title-tooltip__trigger button.atlas-editor__button")
    hideEditor_button = (By.CSS_SELECTOR, "div.editor-trigger__end > span:nth-child(2) > span.nebula-tooltip-trigger > button")
    DE_Logo=(By.CSS_SELECTOR, "img[class='banner-logo']")
    signouttext = (By.CSS_SELECTOR, "div[aria-live='assertive'] div#login_workload_logo_text")
    first_safety_educatortext=(By.CSS_SELECTOR, "span[class*='nebula-breadcrumbs__item-inner--current']")
    pdf_frame=(By.CSS_SELECTOR,"div > div.component-asset-viewer__content-player > div > iframe,.component-row__content .component-asset-embed .component-asset-embed__player-components iframe")
    pdf_open=(By.CSS_SELECTOR, "div[id='dcr_page'] img[id='dcr_pageimage']")
    download_button=(By.CSS_SELECTOR, "div[class='component-button-group__buttons'] a, .component-button-group__buttons button[event-id-emitter*='Download']")
    pdf_header=(By.CSS_SELECTOR,"div[id='dcr_page'] span[class='dcr_sentence s2 r1'],div[id='dcr_page'] span[class='dcr_sentence s3 r2']")
    back_button=(By.CSS_SELECTOR,"div[class='nebula-action-bar__button--back'] a[aria-label='Back'],.nebula-action-bar__button--back,a[aria-label='Exit']")
    video_resource_mydigitallife = (By.CSS_SELECTOR, "ul[class*='nebula-tabs__list--widths-calculated'] li:nth-child(2) a")
    educators_resource_my_digital_life=(By.CSS_SELECTOR,"ul[class*='nebula-tabs__list--widths-calculated'] li:nth-child(2) button[class*='nebula-tabs__tab-dropdown-btn'][aria-label='open menu']")
    educator_guide_button=(By.CSS_SELECTOR,".component-button-group__buttons a[href='/pages/044fcb1f-bcce-4662-8b74-1863109569ce'],.component-button-group__buttons a[href*='/player/280a79f0-f0ee-4d22-8e4c-53fe62590d3e'],.nebula-list-group__content a[href*='/player/280a79f0-f0ee-4d22-8e4c-53fe62590d3e']")
    classroom_activity = (By.CSS_SELECTOR,".component-button-group__buttons a[href*='/player/e32f6a07-31db-46d2-abe2-5381c74377df'],.nebula-list-group.nebula-list-group--nested.nebula-card__links a[href*='c6e4707f-8810-4112-bb55-466ed6e82844'], .nebula-card__content a[href*='c6e4707f-8810-4112-bb55-466ed6e82844']")
    student_activity_button=(By.CSS_SELECTOR,".component-button-group__buttons a[href*='/player/e32f6a07-31db-46d2-abe2-5381c74377df'],.nebula-list-group.nebula-list-group--nested.nebula-card__links a[href*='c6e4707f-8810-4112-bb55-466ed6e82844'], .nebula-card__content a[href*='c6e4707f-8810-4112-bb55-466ed6e82844'], .component-button-group__buttons a[href*='/player/b2c6ba34-1867-4a75-9503-d3807953e13f']")
    mydigitalLife_header=(By.CSS_SELECTOR,"h3.component-feature-item__title, div .component-text-row__title")
    pdf_stop=(By.CSS_SELECTOR,"button[id='dcr_stop']")
    pdf_pause = (By.CSS_SELECTOR, "button[id='dcr_pause']")
    pdf_audioplay = (By.CSS_SELECTOR, "button[id='dcr_play']")
    close_survey_popup_button = (By.CSS_SELECTOR, "button[aria-label='close modal']")
    breadcrumb_nebula_main_text = (By.CSS_SELECTOR, ".nebula-breadcrumbs__link.nebula-breadcrumbs__item-inner")
    tooltips_count = (By.CSS_SELECTOR, "div.editor-trigger__end > span")
    tooltips_index = lambda index: (By.CSS_SELECTOR, "div.editor-trigger__end > span:nth-child({}) > span.nebula-tooltip__tooltip > p".format(index))
    tooltips_select= lambda index: (By.CSS_SELECTOR, "div.editor-trigger__end > span:nth-child({}) > span.nebula-tooltip-trigger > button".format(index))
    mysw_video_asset = (By.CSS_SELECTOR, ".atlas-layout__page>section:nth-child(3)>div:nth-child(2)>div>div>div>a:nth-child(1)>div a.lesson-card__image-link")
    video_asset_duration = (By.CSS_SELECTOR, ".atlas-layout__page>section:nth-child(3)>div:nth-child(2)>div>div>div>a:nth-child(1)>div .lesson-card__tags .nebula-badge--gray")
    video_asset_line1_duration = (By.CSS_SELECTOR, ".lesson-timeline__body div:nth-child(1) .lesson-timeline__item-wrapper time")
    video_asset_line2_duration = (By.CSS_SELECTOR, ".lesson-timeline__body>div:nth-child(2) .nebula-badge__container .lesson-timeline__item-wrapper time")
    back_to_unit = (By.CSS_SELECTOR, "section:nth-child(1) .component-row__content a.component-back-button, .nebula-action-bar__button--back button[aria-label='Back']")
    facilitator_guide_link = (By.CSS_SELECTOR, ".component-button-group__buttons a[href*='54d0854e-ba53-47d6-9398-3f70c7cfd6b8']")
    educator_Resources_hero_image = (By.CSS_SELECTOR, "section[id='6d702000-2b12-4e32-b77f-50d4d2c4a7c8']")
    educator_Resources_title = (By.CSS_SELECTOR, "section[id='7f5a8d42-e3c1-4380-b096-2ffc748485c9'] .component-text__title .nuxt-content")
    educator_Resources_content = (By.CSS_SELECTOR, ".nuxt-content")
    educator_resource_button = (By.CSS_SELECTOR, ".nebula-tabs__list .nebula-tabs__list-item a[href*='d762cf97-e305-45bc-9db6-2467b2019eb9']")
    Professional_Development_link = (By.CSS_SELECTOR, ".nebula-tabs__list-item a[href*='/professional-development']")
    classroommanagement_educator_guide_link = (By.CSS_SELECTOR, ".nebula-list-item.nebula-card__link a[href*='1ff75066-5f41-4070-aa30-542727f79325']")
    Professional_hero_image = (By.CSS_SELECTOR, "section[id='2bec5f25-d83e-4ae7-bf3c-b657dd6f5e90']")
    Professional_title = (By.CSS_SELECTOR, "section[id='ca8af8ff-77de-4028-9cc6-866cad4c9087'] .component-text__title .nuxt-content")
    collections_dropdown = (By.CSS_SELECTOR, ".nebula-tabs__list-item a[href*='37696736-df1a-440c-a87f-3524ec545d1b']+button")
    illegal_collections_option = (By.CSS_SELECTOR, ".component-button-group a[href*='2d43a6f3-9403-46a7-b46c-0b993f46ac2f'], .nebula-list-group__content a[href*='/generation-innovation-illegal-dumping']")
    illegal_CurriculumConnectorPDF = (By.CSS_SELECTOR, ".component-button-group a[href*='382e59d2-cec2-426b-8a96-a78668572b25']")
    illegal_collections_breadcrumb = (By.CSS_SELECTOR, ".nebula-breadcrumbs__item a[href*='2d43a6f3-9403-46a7-b46c-0b993f46ac2f']")
    illegal_ReadyToUse_Activity = (By.CSS_SELECTOR, ".component-button-group a[href*='46d50601-2fc4-4470-8718-512589d78320']")
    illegal_dumping_video_title = (By.CSS_SELECTOR, ".video-player__details h1")
    illegal_dumping_title = (By.CSS_SELECTOR, "section[id='d6f3d8d7-14f5-4552-bf1f-e196ee28910d'] .component-text__title")
    illegal_dumping_content = (By.CSS_SELECTOR, "section[id='d6f3d8d7-14f5-4552-bf1f-e196ee28910d'] .component-text__description .nuxt-content")
    responsible_header_studio = (By.CSS_SELECTOR, "div[id='17957e60-69e0-46c5-8b75-c3e564e904bb'] .studio-text-editor .titan-text-editor")
    responsible_slide1_header = (By.CSS_SELECTOR, "#module-a2382224-8f88-456f-83a0-6897dfe749e4 .studio-text-editor__editor p strong")
    current_slideshow_number = (By.CSS_SELECTOR, "span.board-options__button-name")
    slideshow_icon_text = (By.CSS_SELECTOR, ".studio-board-player__metadata")
    responsible_slide2_header = (By.CSS_SELECTOR, "#module-6bb78ed4-1dff-4b88-93e5-8e52f7095487 .titan-text-editor p")
    animated_topic_series = (By.CSS_SELECTOR, "ul[class*='nebula-tabs__list--widths-calculated'] li:nth-child(2) ul li:nth-child(2) a")
    atlas_list_view_option = (By.CSS_SELECTOR, ".apps-dashboard__filters-end .a-flex-align--start .atlas-editor__button-wrap:nth-child(2) button")
    atlas_list_view_page = (By.CSS_SELECTOR, ".apps-dashboard__filters-end .a-flex-align--start .atlas-editor__button-wrap:nth-child(2) button.nebula-button--active")
    atlas_app_header = (By.CSS_SELECTOR, ".admin-page__content")
    first_searched_atlas_app_card = (By.CSS_SELECTOR, "div.apps-dashboard__grid--list .app-card:nth-child(1) div[class*='app-card__label-title'] a.app-card__label-title-link")
    atlas_app_card_builder_button = (By.CSS_SELECTOR, "div.apps-dashboard__grid--list .app-card:nth-child(1) .app-card__subactions > div.atlas-editor__button-wrap:nth-child(4) button.atlas-editor__button")
    atlas_apps_page_status_dropdown = (By.CSS_SELECTOR, ".apps-dashboard__filters-end .asset-action-dropdown #asset-actions-filters")
    atlas_apps_page_status_dropdown_closed = (By.CSS_SELECTOR, ".apps-dashboard__filters-end .nebula-dropdown:not(.nebula-dropdown--open) #app-status-filters")
    atlas_apps_page_status_dropdown_open = (By.CSS_SELECTOR, ".apps-dashboard__filters-end .nebula-dropdown.nebula-dropdown--open #app-status-filters")
    atlas_apps_page_status_dropdown_all_status_option = (By.CSS_SELECTOR, ".apps-dashboard__filters-end .nebula-dropdown.nebula-dropdown--open .nebula-dropdown__content .nebula-dropdown__item:nth-child(1) button")
    atlas_apps_page_status_dropdown_text = (By.CSS_SELECTOR, ".apps-dashboard__filters-end .nebula-dropdown .nebula-button__text")
    generation_innovation_option = (By.CSS_SELECTOR, ".nebula-card__content a[href*='/generation-innovation'].nebula-card__title")
