from selenium.webdriver.common.by import By


class CommonLocators:
    pageload_component_spinner = (By.CSS_SELECTOR, ".component-spinner__svg,div[id='nuxt-loading'],div[id='nprogress'],.comet-spinner__icon,#nprogress")
    actions_menu_add_to_favorites_teacher = (By.CSS_SELECTOR, ".hidden-for-mobile .tools-tray-tool.tray-more .tools-tray-dropdown__inner .tools-tray-dropdown__column:nth-child(3) button.action-quick-list .comet-button__text")
    actions_menu_add_to_favorites_student = (By.CSS_SELECTOR, ".hidden-for-mobile .tools-tray-tool.tray-more .tools-tray-dropdown__inner .tools-tray-dropdown__column:nth-child(2) button.action-quick-list .comet-button__text")
    actions_menu_close_button = (By.CSS_SELECTOR, '.hidden-for-mobile .tools-tray-tool.tray-more .tools-tray-dropdown__close-button')
    actions_menu_create_with_studio = (By.CSS_SELECTOR, '.hidden-for-mobile .tools-tray-tool.tray-more button.action-studio .comet-button__text')
    actions_menu_remove_from_favorites_student = (By.CSS_SELECTOR, ".hidden-for-mobile .tools-tray-tool.tray-more .tools-tray-dropdown__inner .tools-tray-dropdown__column:nth-child(2) button.action-quick-list .comet-button__text")
    actions_menu_remove_from_favorites_teacher = (By.CSS_SELECTOR, ".hidden-for-mobile .tools-tray-tool.tray-more .tools-tray-dropdown__inner .tools-tray-dropdown__column:nth-child(3) button.action-quick-list.active .comet-button__text")
    actions_menu_options_menu_all_options = lambda option_index: (By.CSS_SELECTOR, ".nebula-dropdown--open .nebula-dropdown__content .nebula-dropdown__item:nth-of-type({}) .nebula-dropdown-item__text".format(option_index))
    action_menu_mycontent_folder = (By.CSS_SELECTOR, "td[data-label='Actions'] button")
    status_checkbox = (By.CSS_SELECTOR, ".assignment-list__dropdown-content>label>span[class='nebula-checkbox__text']")
    active_checkbox = (By.CSS_SELECTOR, "div[aria-labelledby='date-status-trigger'] >div>:nth-child(2)")
    apply_button = (By.CSS_SELECTOR, ".assignment-list__filter-container>button[aria-label='Apply Filters']")
    assign_action_menu_mycontent_folder = (By.CSS_SELECTOR, "[aria-labelledby='my-content-table-actions__dropdown-button--1'] li[data-click-name='Assign'] a")
    asset_card_menu_options = (By.CSS_SELECTOR,'.nebula-dropdown--open .nebula-dropdown__content .nebula-dropdown__item .nebula-dropdown-item__text')
    agree_button_terms_and_conditions = (By.CSS_SELECTOR, "div.comet-row form button[name='accept']")
    asset_more_actions_assign_button = (By.CSS_SELECTOR, "ul.actions-list.visible li.action:nth-child(2) a")
    assignment_homepage = (By.CSS_SELECTOR, ".nebula-product-bar__page-title")
    assignment_status = (By.CSS_SELECTOR, ".assignment-list__dropdown>button[id='date-status-trigger']")
    assignment_card = (By.CSS_SELECTOR, ".nebula-card-row .nebula-card ,nebula-card ")
    long_assignment_card = (By.CSS_SELECTOR, ".long-assignment-card__assignment-information")
    assignment_card_asset_name = (By.CSS_SELECTOR, "div[class='nebula-card__content']>a[class='nebula-card__title']")
    assignment_card_class_name = (By.CSS_SELECTOR, ".nebula-card__description>p[class*='nebula-card__classroom']")
    assignment_card_due_in_icon = (By.CSS_SELECTOR, ".nebula-card__content>div>span[class='assignment-due-in']")
    assignment_card_due_in_time = (By.CSS_SELECTOR, ".nebula-card__content>div>span[class='assignment-due-in']>label")
    assignment_cancel_button = (By.CSS_SELECTOR, ".nebula-modal__container>div[class*='nebula-modal__actions-container']>button")
    assignment_title_student = (By.CSS_SELECTOR, ".section-header__title")
    assignment_card_teacher_name = (By.CSS_SELECTOR, ".nebula-card__description>p[class*='nebula-card__teacher']")
    assignment_card_status = (By.CSS_SELECTOR, ".nebula-badge__container>div")
    assignment_add_date_button = (By.CSS_SELECTOR, ".assign-form__button.assign-form__button--step2:not(.comet-modal__button--cancel)")
    assignment_assign_button = (By.CSS_SELECTOR, ".comet-modal__button-row.assign-form__buttons.assign-form__buttons--step-3 .comet-button.comet-button--primary.comet-modal__button.comet-modal__button--assign,.assign-page__action-button.nebula-button--square.nebula-button--fill")
    assignment_assign_date = (By.CSS_SELECTOR, "#assign-date")
    assignment_back_button_on_step2 = (By.CSS_SELECTOR, ".assign-form__buttons--step-2 .assign-form__button.assign-form__button--step1,.assign-page__action-button.nebula-button--square.nebula-button--ghost")
    assignment_back_button_on_step3 = (By.CSS_SELECTOR, ".assign-form__buttons--step-3 .assign-form__button.assign-form__button--step2,.assign-page__action-button.nebula-button--square.nebula-button--ghost")
    assignment_class_checkbox = lambda index: (By.CSS_SELECTOR, ".assign-step__classrooms-container .assign-step__classroom:nth-child({}) .nebula-checkbox__visual".format(index))
    assignment_class_checkbox_checked = lambda index: (By.CSS_SELECTOR, ".assign-step__classrooms-container .assign-step__classroom:nth-child({}) .nebula-checkbox__visual .nebula-checkbox__checked-icon".format(index))
    assignment_description = (By.CSS_SELECTOR, "#assign-instructions.comet-form__textarea,.assign-step__field-group-container:nth-child(2) .assign-step__textarea.nebula-textarea")
    assignment_due_assign_date = (By.CSS_SELECTOR, "#due-date")
    assignment_multiple_class_checkbox = (By.CSS_SELECTOR, ".assign-step__classrooms-container .assign-step__classroom .nebula-checkbox__text")
    assignment_name_by_index = lambda index: (By.CSS_SELECTOR, "tbody tr.nebula-table__row:nth-child({}) a.assignment-link-list__table-link".format(index))
    assignment_okay_button = (By.CSS_SELECTOR, ".assign-page__assign-button.nebula-button--square.nebula-button--fill")
    assignment_view_all_button = (By.CSS_SELECTOR, "a[href*='/learn/assignment'].assign-page__action-button")
    assignment_Next_button = (By.CSS_SELECTOR, ".assign-page__action-button.nebula-button--square.nebula-button--fill")
    assignment_select_class_button = (By.CSS_SELECTOR, ".nebula-checkbox.assign-step__checkbox-input")
    assignment_student_selected_link = lambda index: (By.CSS_SELECTOR, ".assign-step__classroom:nth-of-type({}) .assign-step__select-students button".format(index))
    assignment_successful_header = (By.CSS_SELECTOR, "div.assign-assignment div.comet-modal__header h3,.assign-step.assign-step--four .assign-step__heading-container p")
    assignment_successfuly_assigned_page_dates = lambda index: (By.CSS_SELECTOR, ".assign-step__group.assign-step__group--info .assign-step__dates p:nth-child({})".format(index))
    assignment_landing_page_active = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(1)>a:nth-child(1))[aria-current='true']")
    assignment_landing_page_overdue = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(1)>a:nth-child(2))[aria-current='true']")
    assignment_landing_page_due_today = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(1)>a:nth-child(3))[aria-current='true']")
    assignment_landing_page_done = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(2)>a:nth-child(1))[aria-current='true']")
    assignment_title = (By.CSS_SELECTOR, "#assign-title.comet-form__input,.assign-step__field-group-container:nth-child(1) .assign-step__textarea.nebula-textarea")
    assignment_view_assignment_manager_button = (By.CSS_SELECTOR, ".assign-assignment .comet-modal__button--cancel,.assign-page__action-button.nebula-button--square.nebula-button--fill")
    assignment_tile_active = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(1)>a:nth-child(1)>span[class*='assignments-dashboard__card-label']")
    assignment_tile_overdue = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(1)>a:nth-child(2)>span[class*='assignments-dashboard__card-label']")
    assignment_tile_due_today = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(1)>a:nth-child(3)>span[class*='assignments-dashboard__card-label']")
    assignment_tile_done_text = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(2)>a:nth-child(1)>span[class*='assignments-dashboard__card-label']")
    assignment_tile_done = (By.CSS_SELECTOR, ".assignments-dashboard>div:nth-child(1)>div:nth-child(2)>a[data-click-name='Done Assignments']")
    assignment_status_complete_text = (By.CSS_SELECTOR, ".long-assignment-card__assignment-details-container>span[class='assignment-status-badge']>div>div")
    assignment_modal_complete_status_text = (By.CSS_SELECTOR, ".assignment-modal__assignment-details-container>span[class='assignment-status-badge']>div>div")
    assignment_completed_text = (By.CSS_SELECTOR, ".asset-detail-page__player-actions>div>div[class='assignment-completed']>p")
    assignments_option = (By.CSS_SELECTOR, "nav:nth-child(2) > section:nth-child(2) a[href*='/assignments'] h3,a[href*='/assignments'] h3")
    assignment_active_card = (By.CSS_SELECTOR, "div[class='assignments-dashboard__card-group']>a>span[class='assignments-dashboard__card-label']")
    assignment_active_no_text = (By.CSS_SELECTOR,".assignments-dashboard__desktop a[data-click-name='Active Assignments'] .assignments-dashboard__card-count")
    assignment_no_of_done_text = (By.CSS_SELECTOR,".assignments-dashboard__desktop a[data-click-name='Done Assignments'] .assignments-dashboard__card-count")
    assignment_done_Tab = (By.CSS_SELECTOR, ".assignments-dashboard__desktop a[data-click-name='Done Assignments']")
    assignment_done_Tab_Active = (By.CSS_SELECTOR,".assignments-dashboard__desktop a[data-click-name='Done Assignments'].assignments-dashboard__done.do-push-state.active")
    assign_modal_image_tumbnail = (By.CSS_SELECTOR,".assignment-modal__asset-thumbnail")
    assign_modal_clock_icon = (By.CSS_SELECTOR, ".assignment-modal__due-in .assignment-due-in__icon--clock")
    assign_modal_timeleft_text = (By.CSS_SELECTOR, ".assignment-modal__asset-details .assignment-due-in__label.assignment-due-in__label--clock")
    assign_modal_asset_title_text = (By.CSS_SELECTOR, ".assignment-modal__asset-details .assignment-modal__title")
    assign_modal_creation_date_text = (By.CSS_SELECTOR, ".assignment-modal__assignment-details-container .assignment-modal__assignment-creation-date")
    assign_modal_due_date_text = (By.CSS_SELECTOR, ".assignment-modal__assignment-details-container .assignment-modal__assignment-due-date")
    assign_modal_classroom_name_text = (By.CSS_SELECTOR, ".assignment-modal__assignment-details-container .assignment-modal__assignment-classroom")
    assign_modal_teachername_text = (By.CSS_SELECTOR, ".assignment-modal__assignment-details-container .assignment-modal__assignment-teacher")
    assign_modal_status_batch_text = (By.CSS_SELECTOR, ".assignment-modal__assignment-details-container .assignment-status-badge")
    assign_modal_instructionTitle = (By.CSS_SELECTOR, ".assignment-modal__instructions .assignment-modal__title")
    Instruction_description_Text = (By.CSS_SELECTOR, ".assignment-modal__instructions .assignment-modal__paragraph")
    assign_modal_asset_type_text = (By.CSS_SELECTOR, ".assignment-modal__instructions .nebula-badge.nebula-badge--outline")
    assign_modal_open_button = (By.CSS_SELECTOR, ".assignment-modal__button--open")
    assign_modal_cancel_button = (By.CSS_SELECTOR, ".assignment-modal__button--close")
    assignment_asset_title_text = (By.CSS_SELECTOR, ".asset-detail-page-header h1")
    avatar_image = (By.CSS_SELECTOR, ".student-profile-page__panel-header .avatar-image>img")
    avatar_tab = (By.CSS_SELECTOR, ".sub-nav__items >li:nth-child(2)>a")
    assignToolBarbutton = (By.CSS_SELECTOR, ".action-assign-link.tools-tray-tool-item")
    archive_old_classes_popup_model_handing = (By.CSS_SELECTOR, "h3[class='archive-classrooms-modal__heading']")
    assignment_pop_up_text = (By.CSS_SELECTOR, "div[class*='nebula-modal__actions-container--sticky'] > a>span")
    assignment_pop_up_button = (By.CSS_SELECTOR, "div[class*='nebula-modal__actions-container--sticky'] > a")
    assign_previous_button = (By.CSS_SELECTOR, "div[class='assign-page__button-container'] button[class*='nebula-button--ghost']")
    assign_to_classroom_option_button = (By.CSS_SELECTOR, ".dual-assign-option__text-and-button button[data-click-type='Assign to DE classroom']")
    assign_to_count_text = (By.CSS_SELECTOR, "div[class='assign-step-tab__number-container assign-step-tab__number-container--current'] p")
    remind_me_later_button = (By.CSS_SELECTOR, ".archive-classrooms-modal__actions .nebula-button--square.nebula-button--flat")
    course_homepage_grade_6_12_text = (By.CSS_SELECTOR, ".techbook-masthead__header>div>h1")
    course_page_grade_card = lambda index: (By.CSS_SELECTOR, ".techbook-orientation__courses>div:nth-child({})>div>a".format(index))
    total_course_page_grade_card = (By.CSS_SELECTOR,".techbook-orientation__courses>div>div>a")
    circle_check_icon = (By.CSS_SELECTOR, ".asset-detail-page__player-actions>div>div[class='assignment-completed']>svg>use")
    classrooms_assignments_tab = (By.CSS_SELECTOR, ".comet-list-group__row a[href='/learn/assignments'],a[href='/learn/assignments']")
    classrooms_assignments_tab_selected = (By.CSS_SELECTOR, "div> a[href='/learn/assignments']")
    create_with_studio_modal_title = (By.CSS_SELECTOR, "div.nebula-modal__content-container h3")
    create_with_studio_popup_modal_type = (By.CSS_SELECTOR, "#studio-create-form-select")
    create_with_studio_popup_cancel_button = (By.CSS_SELECTOR, ".nebula-modal__actions-container button.nebula-button.nebula-button--m.nebula-button--square.nebula-button--ghost .nebula-button__text")
    create_with_studio_popup_header = (By.CSS_SELECTOR, " div > div.nebula-modal__x-button-container")
    create_with_studio_popup_start_creating_button = (By.CSS_SELECTOR, ".nebula-modal__container button.nebula-button.nebula-button--m.nebula-button--square.nebula-button--fill")
    create_with_studio_popup_thumbnail = (By.CSS_SELECTOR, "div[class*='studio-modal__thumbnail-container']")
    celltheoryconcept = (By.CSS_SELECTOR, "a[href='/learn/techbook/units/3391ad2d-bceb-45dc-a68b-8fd21ab33671/concepts/347de6c1-d9af-44b6-8286-e5a02996035b']")
    close_pop_up_button = (By.CSS_SELECTOR, "div[class*='nebula-modal__actions-container--sticky'] > button")
    close_pop_up_button_text = (By.CSS_SELECTOR, "div[class*='nebula-modal__actions-container--sticky'] > button>span")
    details_tab = (By.CSS_SELECTOR, "ul[class*='sub-nav__items'] >li:nth-child(1)>a")
    de_logo = (By.CSS_SELECTOR, ".top-nav__de-icon,.nebula-product-bar .nebula-product-bar__home")
    done_label_text = (By.CSS_SELECTOR, ".long-assignment-card__due-in>label[class*='assignment-due-in__label']")
    explore_homepage = (By.CSS_SELECTOR, ".nebula-product-bar__inline-start>div>div[class*='nebula-product-bar__page-title']")
    explore_tab = (By.CSS_SELECTOR, ".sub-nav__item a[href='/learn/explore']")
    explore_tab_BrowsebySubject_Title_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject']")
    explore_tab_Science_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Science']")
    explore_tab_SocialStudies_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Social Studies']")
    explore_tab_English_Arts_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='English/Language Arts']")
    explore_tab_Mathematics_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Mathematics']")
    explore_tab_Health_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Health']")
    explore_tab_careers_hub_t4_subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Careers Hub']")
    explore_tab_Visual_PerformingArts_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Visual and Performing Arts']")
    explore_tab_Multi_Language_Resources_T4Subject = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Multi-Language Resources']")
    explore_tab_Science_T4Subject_Icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Science'] .nebula-card__icon--science")
    explore_tab_SocialStudies_T4Subject_Icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Social Studies'] .nebula-card__icon--social-studies")
    explore_tab_English_Arts_T4Subject_Icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='English/Language Arts'] .nebula-card__icon--english-language-arts")
    explore_tab_Mathematics_T4Subject_Icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Mathematics'] .nebula-card__icon--math")
    explore_tab_Health_T4Subject_Icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Health'] .nebula-card__icon--health")
    explore_tab_careers_hub_t4_subject_icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Careers Hub'] .nebula-card__icon--feedback-bug")
    explore_tab_Visual_PerformingArts_T4Subject_Icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Visual and Performing Arts'] .nebula-card__icon--visual-and-performing-arts")
    explore_tab_Multi_Language_Resources_T4Subject_Icon = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Multi-Language Resources'] .nebula-card__icon--languages")
    explore_tab_BrowsebySubject_Title_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] h3")
    explore_tab_Science_T4Subject_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Science'] span")
    explore_tab_SocialStudies_T4Subject_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Social Studies'] span")
    explore_tab_English_Arts_T4Subject_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='English/Language Arts'] span")
    explore_tab_Mathematics_T4Subject_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Mathematics'] span")
    explore_tab_Health_T4Subject_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Health'] span")
    explore_tab_careers_hub_t4_subject_text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Careers Hub'] span")
    explore_tab_Visual_PerformingArts_T4Subject_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Visual and Performing Arts'] span")
    explore_tab_Multi_Language_Resources_T4Subject_Text = (By.CSS_SELECTOR, "div[aria-label='Browse by Subject'] a[data-click-name='Multi-Language Resources'] span")
    glossary_window_dropdown = lambda index: (By.CSS_SELECTOR, "div[class='glossary-navigation-container']>div:nth-child({})>button>span>span>span:nth-child(2)".format(index))
    glossary_window_allconcept=(By.CSS_SELECTOR,"div[class='glossary-navigation-container']>div[class='glossary-navigation-dropdown']:nth-child(2)>button[class*='comet-button--disabled']>span")
    glossary_window_header = (By.CSS_SELECTOR, "div.glossary-header a")
    glossary_window_header_text=(By.CSS_SELECTOR,"div.glossary-header a span[class='comet-button__inner']")
    grade_button = lambda grade : (By.CSS_SELECTOR, ".onboarding-container__interests-button[for='{}'] input".format(grade))
    grade_button_selected = lambda grade : (By.CSS_SELECTOR, ".onboarding-container__interests-button.comet-button--checked[for='{}'] input".format(grade))
    great_work_text = (By.CSS_SELECTOR, ".nebula-modal__container>div>div> [id*='mark-as-complete-modal__header']")
    student_homepage_avatar_image = (By.CSS_SELECTOR, ".student-homepage__welcome>div>a")
    homepage_dashboard_message = (By.CSS_SELECTOR, ".student-homepage__welcome>div[class='student-homepage__welcome-right']>div")
    homepage_scienceTB_dropdown = (By.CSS_SELECTOR, ".techbook-entry__panel--DETB select[name='course_id']")
    homepage_mathTB_dropdown = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB select[name='course_id']")
    homepage_scienceTB_go_button_disabled = (By.CSS_SELECTOR, ".techbook-entry__panel--DETB button[class='nebula-button nebula-button--l nebula-button--square nebula-button--fill']")
    homepage_mathTB_go_button_disabled = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB button[class='nebula-button nebula-button--l nebula-button--square nebula-button--fill']")
    homepage_scienceTB_go_button = (By.CSS_SELECTOR, ".techbook-entry__panel--DETB div[class='nebula-field-group--horizontal'] a[data-click-name='Go']")
    homepage_mathTB_go_button = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB div[class='nebula-field-group--horizontal'] a[data-click-name='Go']")
    homepage_socialTB_dropdown = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS select[name='course_id']")
    homepage_socialTB_go_button_disabled = (By.CSS_SELECTOR,".techbook-entry__panel--SOCS button[class='nebula-button nebula-button--l nebula-button--square nebula-button--fill']")
    homepage_socialTB_go_button = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS div[class='nebula-field-group--horizontal'] a[data-click-name='Go']")
    home_page_techbook_card = lambda tb_card: (By.CSS_SELECTOR, "a[href*='courses/{}']".format(tb_card))
    home_tab = (By.CSS_SELECTOR, ".sub-nav__item a[href='/learn/students']")
    homepage_techbook_grade_dropdown = (By.CSS_SELECTOR, ".techbook-course-selector__courses .nebula-select__element")
    homepage_goToTechbookCourse_button = (By.CSS_SELECTOR, ".techbook-course-selector__courses a[data-click-name*='Launch']")
    homepage_techbook_Tabcourse_dropdown = (By.CSS_SELECTOR, "div[id='techbook-course-selector__content--0'] h1 + .techbook-course-selector__courses  .nebula-select__element")
    homepage_goToTechbookTabCourse_button = (By.CSS_SELECTOR, "div[id='techbook-course-selector__content--0'] h1 + .techbook-course-selector__courses a[data-click-name*='Launch']")
    join_live_activity_tab = (By.CSS_SELECTOR, ".sub-nav__join-activity-button:nth-child(1)")
    join_live_activity_container = (By.CSS_SELECTOR, ".nebula-modal__content-container,#engage_activity_entry")
    looking_for_more_title = (By.CSS_SELECTOR, ".section-header>div>h3")
    loading_spinner_image = (By.CSS_SELECTOR, "div.spinner")
    lifesciencecourse = (By.CSS_SELECTOR, "a[href='/learn/techbook/courses/747280fc-f038-427d-a400-b5d4a59a0f6d']")
    my_classroom_tab = (By.CSS_SELECTOR, "a[data-click-name='Assignments'] div[class='nebula-global-nav-item__summary']")
    my_content_homepage = (By.CSS_SELECTOR, ".nebula-product-bar__inline-start>div>div[class*='nebula-product-bar__page-title']")
    myde_logo_studio = (By.CSS_SELECTOR, "div[class='top-nav__contents']>a.top-nav__de-link,.nebula-product-bar .nebula-product-bar__home")
    myde_logo_studio_stem = (By.CSS_SELECTOR, "#comet-navigation > div > img, .nebula-product-bar__inline-start a")
    mark_as_complete_checkbox = (By.CSS_SELECTOR, "button.mark-as-complete-btn")
    mark_as_complete_button = (By.CSS_SELECTOR, ".asset-detail-page__assignment .nebula-button--fill,.asset-detail-page__action-button.nebula-button--square.nebula-button--fill")
    mark_as_complete_pop_up_yes_btn = (By.CSS_SELECTOR, "button[id*='mark-as-complete-modal__button--primary']")
    mark_as_complete_pop_up_yes_text = (By.CSS_SELECTOR, "button[id*='mark-as-complete-modal__button--primary'] span")
    mark_as_complete_pop_up_not_yet_text = (By.CSS_SELECTOR, ".nebula-modal__actions-container--sticky .nebula-button--ghost>span")
    next_button = (By.CSS_SELECTOR, ".editor__nav-button--rounded,button[aria-label='Next Slide']")
    on_boarding_guide_pop_up = (By.CSS_SELECTOR, "div[data-vertical-alignment='Relative to Element']>div[id*='pendo-guide-container']>div>div>div>button")
    previous_button = (By.CSS_SELECTOR, ".editor__nav-button--prev.editor__nav-button--rounded,button[aria-label='Previous Slide']")
    previous_button_disabled = (By.CSS_SELECTOR, ".editor__nav-button--rounded,button[aria-label='Previous Slide'][aria-disabled='true']")
    profile_back_arrow = (By.CSS_SELECTOR, ".sub-nav__bar >div>a")
    profile_full_name = (By.CSS_SELECTOR, ".student-profile-page__panel-header>h5")
    profile_user_name_label = (By.CSS_SELECTOR, ".student-profile-page__panel-section>div:nth-child(2)>label")
    profile_school_label = (By.CSS_SELECTOR, ".student-profile-page__panel-section>div:nth-child(3)>label")
    profile_grade_label = (By.CSS_SELECTOR, ".student-profile-page__panel-section>div:nth-child(4)>label")
    profile_info_in_details_page = (By.CSS_SELECTOR, ".student-profile-page__panel-section>p")
    profilesetup_termsandconditioncheckbox = (By.CSS_SELECTOR, ".welcome-page__terms input[name='terms']")
    profilesetup_termsandconditionacceptbutton = (By.CSS_SELECTOR, ".welcome-page__agree.nebula-button--square.nebula-button--fill:not([data-click-name='false'])[data-click-name='Terms - Next - Update Profile']")
    profilesetup_nextjobtittle = (By.CSS_SELECTOR, "a[href*='/learn/welcome/'][data-click-name='Next - Job Title']")
    profilesetup_welcome_page_header = (By.CSS_SELECTOR, ".welcome-page__header")
    profilesetup_profilesetupcontinuebutton = (By.CSS_SELECTOR, "a[href*='/learn/welcome/']")
    profilesetup_teacherjobtitle = (By.CSS_SELECTOR, "div[class='nebula-checkbox-group welcome-page__buttons'] label.nebula-radio__container input[value='Teacher'] ")
    profilesetup_nextgradelevel = (By.CSS_SELECTOR, "a[href*='/learn/welcome/'][data-click-name='Next - Grade Level']:not([style*='display'])")
    profilesetup_profilesetup_allselect = (By.CSS_SELECTOR, "input[id='all']")
    profilesetup_preKgradeselect = (By.CSS_SELECTOR, "input[id='grade-pre-k']")
    profilesetup_nextsubject = (By.CSS_SELECTOR, "[data-click-name='Next - Subjects']:not([style*='display'])")
    profilesetup_sciencesubject = (By.CSS_SELECTOR, "input[id='subject-science']")
    profilesetup_nexttopics = (By.CSS_SELECTOR, "[data-click-name='Next - Topics']:not([style*='display'])")
    profilesetup_nextcontent = (By.CSS_SELECTOR, "[data-click-name='Next - Content']:not([style*='display'])")
    profilesetup_stemtopicselect = (By.CSS_SELECTOR, "input[id='topic-stem']")
    profilesetup_allcontentcheckbox = (By.CSS_SELECTOR, "input[id='all-content']")
    profilesetup_activitiesforyou = (By.CSS_SELECTOR, "input[id='category-activities-for-you']")
    profilesetup_nextfinish = (By.CSS_SELECTOR, "[data-click-name='Content - Finish']:not([style*='display'])")
    profilesetup_nextcurriculum = (By.CSS_SELECTOR, "[data-click-name='Next - Curriculum']:not([style*='display'])")
    profilesetup_curriculumfinish = (By.CSS_SELECTOR, "[data-click-name='Curriculum - Finish']:not([style*='display'])")
    physical_science_header_in_toc = (By.CSS_SELECTOR, ".toc-modal__sub-wrapper-theme--physical-science .toc-modal__sub-title")
    favorites_added_message = (By.CSS_SELECTOR, "div>[class='nebula-toast-message__content nebula-toast-message__content--flex-row']>span")
    favorites_button_in_top_nav = (By.CSS_SELECTOR, "button[aria-label='Open Favorites'],button[aria-label='Abrir Lista rápida'], button[aria-label='Abrir favoritos']")
    favorites_button_in_top_nav_new = (By.CSS_SELECTOR,"button[aria-label='Open Favorites']")
    favorites_count = (By.CSS_SELECTOR,"#comet-product-bar__quicklist-button>span:nth-child(1),.nebula-quicklist-panel__count span:nth-child(2),button[aria-label='Open Favorites']")
    favorites_count_in_panel = (By.CSS_SELECTOR,".comet-page-shell__panel--quicklist__header .comet-product-bar__quicklist-button>span:nth-child(1),.nebula-quicklist-panel__count span:nth-child(2)")
    favorites_count_in_panel_new = (By.CSS_SELECTOR,".comet-page-shell__panel.quicklist .comet-product-bar__quicklist-button span:nth-child(1),.nebula-quicklist-panel__count span:nth-child(2)")
    favorites_notification_message = (By.CSS_SELECTOR, ".comet-toast-message__inner .comet-toast-message__text-container .comet-toast-message__text,.nebula-toast-message__content span")
    favorites_notification_close = (By.CSS_SELECTOR, ".comet-toast-message__close,button[aria-label='close']")
    favorites_options_disabled = (By.CSS_SELECTOR, "#quicklist__list-options.comet-page-shell__panel--quicklist-list-option__action-bar-item--disabled")
    favorites_options = (By.CSS_SELECTOR,"#quicklist__list-options,.nebula-quicklist-panel__action .nebula-button--pill.nebula-button--flat")
    favorites_panel_active = (By.CSS_SELECTOR, ".nebula-quicklist-panel__title")
    favorites_panel_active_new = (By.CSS_SELECTOR, ".comet-page-shell__panel.quicklist .quicklist__heading,.nebula-quicklist-panel__title")
    favorites_panel_asset_title = (By.CSS_SELECTOR, "h3.nebula-quicklist-card__title>a")
    favorites_panel_asset_title_new = (By.CSS_SELECTOR, "h3.nebula-quicklist-card__title>a")
    favorites_panel_close = (By.CSS_SELECTOR, "button[aria-label='Close']")
    favorites_panel_close_new = (By.CSS_SELECTOR, ".comet-page-shell__panel.quicklist .comet-page-shell__close-panel,button[aria-label='Close']")
    favorites_remove_all_option = (By.CSS_SELECTOR,"button[data-gal*='RemoveAll'],ul[aria-labelledby='quicklist-action-menu'] .nebula-dropdown__item:nth-child(2) button")
    favorites_menu_all_options = (By.CSS_SELECTOR, "ul[aria-labelledby*='quicklist-action-menu'] button")
    favorites_menu_options_by_index = lambda index: (By.CSS_SELECTOR, "ul[aria-labelledby*='quicklist-action-menu'] li:nth-child({}) button".format(index))
    favorites_remove_all_popup_button = (By.CSS_SELECTOR,".remove-all-quicklist .btn-set a.action-btn,.nebula-modal__inner .nebula-modal__actions-container .nebula-button--square.nebula-button--fill")
    favorites_remove_all_popup_button_new = (By.CSS_SELECTOR, "#QuicklistConfirmRemoveAll .comet-button--danger,.nebula-modal__actions-container .nebula-button.nebula-button--square.nebula-button--fill")
    robot_avatar_image = (By.CSS_SELECTOR, ".fallback-cards__image-container>img")
    reading_robot_image = (By.CSS_SELECTOR, ".assignments-dashboard__character-image")
    science_tab_icon = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--DETB']>button>div>svg:nth-child(1)>use, #science-flask")
    science_tab_name = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--DETB']>button>div>svg:nth-child(1)>use, #science-techbook-logo")
    see_all_assignment_button = (By.CSS_SELECTOR, ".section-header>div>a")
    search_homepage = (By.CSS_SELECTOR, ".nebula-product-bar__inline-start>div>div[class*='nebula-product-bar__page-title']")
    search_button = (By.CSS_SELECTOR, "div.comet-product-bar-container button.comet-button.comet-button--icon-only.comet-product-bar__search-button.global-nav-ga-event,.nebula-product-bar__search-button")
    search_page_asset_action_button = lambda index: (By.CSS_SELECTOR, "li.nebula-container-card:nth-child({}) .nebula-card__action-menu button[id*='action-menu'], li.nebula-card:nth-child({}) .nebula-card__action-menu button[id*='action-menu']".format(index, index))
    search_page_asset_thumbnail_by_index = lambda index: (By.CSS_SELECTOR, "[data-index*='Result number: {}'] button[class*='preview-button'], [data-index*='Result number: {}'] img.nebula-image".format(index, index))
    search_page_asset_action_button_clicked = lambda index: (By.CSS_SELECTOR, "li.nebula-container-card:nth-child({}) .nebula-card__action-menu button[id*='action-menu'][aria-expanded='true'], li.nebula-card:nth-child({}) .nebula-card__action-menu button[id*='action-menu'][aria-expanded='true']".format(index, index))
    search_page_asset_action_favorites_button = lambda index: (By.CSS_SELECTOR, ".search-cards-container li.nebula-card:nth-child({}) .action-quick-list".format(index))
    search_page_asset_action_save_button = lambda index: (By.CSS_SELECTOR, ".search-cards-container li.nebula-card:nth-child({}) .action-save".format(index))
    search_page_asset_container = lambda index: (By.CSS_SELECTOR, ".search-cards-container li.nebula-card:not(.nebula-card--invisible):nth-child({})".format(index))
    search_page_cards = (By.CSS_SELECTOR, "li.nebula-container-card, li.nebula-card:not(.nebula-card--invisible)")
    search_page_card_container_thumbnail = (By.CSS_SELECTOR, ".nebula-card .nebula-thumbnail__inner--thumbnail-loaded")
    search_page_card_title = lambda index: (By.CSS_SELECTOR, "li.nebula-container-card:nth-child({}) .nebula-card__title, li.nebula-card:nth-child({}) .nebula-card__title".format(index, index))
    search_page_card_type = lambda index: (By.CSS_SELECTOR, "li.nebula-container-card:nth-child({}) .nebula-card__type, li.nebula-container-card:nth-child({}) .nebula-card__type".format(index, index))
    search_page_filter_by_index = lambda index: (By.CSS_SELECTOR, ".asset-type-filters__list .asset-type-filters__list-item:nth-child({}) a".format(index))
    search_page_filter_by_index_selected = lambda index: (By.CSS_SELECTOR, ".asset-type-filters__list .asset-type-filters__list-item.current:nth-child({}) a".format(index))
    search_text_field = (By.CSS_SELECTOR, "#comet-product-bar__search-input,.nebula-product-bar__search-input")
    search_text_card_result = (By.CSS_SELECTOR, ".nebula-container-card .nebula-card__title")
    search_page_channel_card = lambda index: (By.CSS_SELECTOR, ".nebula-card--channel:nth-child({})".format(index))
    select_all_grades_button = (By.CSS_SELECTOR, ".grades__select-all-button:not(.comet-button--checked)")
    share_modal_close_button = (By.CSS_SELECTOR, "div>button[aria-label='close modal']")
    share_modal_copy_button = (By.CSS_SELECTOR, "#copy-button")
    share_modal_header = (By.CSS_SELECTOR, "div> h2[class='share-modal__heading']")
    share_modal_copied_button = (By.CSS_SELECTOR, "#copy-button")
    share_modal_link_textbox = (By.CSS_SELECTOR, ".comet-form__input.share-modal__input,div.nebula-field-group input")
    studio_content_page = (By.CSS_SELECTOR, ".editor__zoom-content")
    studio_de_icon = (By.CSS_SELECTOR, ".top-nav__de-icon,.nebula-product-bar .nebula-product-bar__home")
    studio_home_mystudiotext = (By.CSS_SELECTOR, ".studio-home__header")
    studio_homepage = (By.CSS_SELECTOR, ".nebula-product-bar__inline-start>div>div[class*='nebula-product-bar__page-title']")
    studio_home_button = (By.CSS_SELECTOR, ".top-nav__studio-link")
    studio_publish_board = (By.CSS_SELECTOR, ".top-nav__actions .comet-button.top-nav__share-button,.top-nav__actions .top-nav__share-button,.top-nav__collaboration-input-wrapper--sharing-modal button")
    studio_title = (By.CSS_SELECTOR, ".top-nav__contents .board-options__button-name")
    studio_filter_dropdown = (By.CSS_SELECTOR, ".board-filters>div>div:nth-child(1)")
    studio_sort_dropdown = (By.CSS_SELECTOR, ".board-filters>div>div:nth-child(2)")
    studio_trash_tab = (By.CSS_SELECTOR, ".nebula-sidebar__section a[href='/trash']")
    studio_trash_homepage_title = (By.CSS_SELECTOR, "div[class='studio-home__main'] h1")
    studio_trash_tab_selected = (By.CSS_SELECTOR, "a[href='/trash'].home-sidebar__list-link--active")
    studio_trash_thumbnail = (By.CSS_SELECTOR, ".board-list.board-list--grid .board-card--grid:nth-child(1) .board-card__board-preview-image")
    studio_trash_sort_filter_lable = (By.CSS_SELECTOR, ".studio-home__main .nebula-label")
    studio_trash_sort_desc = (By.CSS_SELECTOR, ".nebula-select .nebula-select__element option:nth-child(1)")
    studio_trash_sort_asc = (By.CSS_SELECTOR, ".nebula-select .nebula-select__element option:nth-child(2)")
    studio_trash_board_title = (By.CSS_SELECTOR, ".board-list.board-list--grid .board-card--grid:nth-child(1) .nebula-card__type")
    studio_trash_board_title_mycontent = (By.CSS_SELECTOR, ".nebula-table__row:nth-child(1) .nebula-table__cell:nth-child(2)")
    studio_trash_ellipse_button = (By.CSS_SELECTOR, ".board-listing-options__dropdown-trigger,.nebula-card.board-card.board-card--grid:nth-child(1) .board-listing-options .nebula-dropdown .nebula-button")
    studio_trash_restore_option_text = (By.CSS_SELECTOR, ".nebula-dropdown.nebula-dropdown--open span")
    studio_trash_restore_option = (By.CSS_SELECTOR, ".nebula-dropdown.nebula-dropdown--open .nebula-dropdown-item__inner")
    studio_trash_restore_modal_x_button  = (By.CSS_SELECTOR, ".comet-modal__inner.modal__inner button[aria-label='Close']")
    studio_trash_restore_modal_cancel_button = (By.CSS_SELECTOR, ".comet-modal__button--cancel")
    studio_trash_restore_modal_MovetoMyStudio_button = (By.CSS_SELECTOR, ".comet-modal__button-row .nebula-button--fill")
    suite_page_classrooms_card = (By.CSS_SELECTOR, ".color-card--classrooms a[href*='/learn/assignments'] p,a[href*='/learn/assignments'] p")
    subject_menu = (By.CSS_SELECTOR, "a[href='/learn/channels/subjects']")
    subject_menu_content = (By.CSS_SELECTOR, ".channels-hero__content")
    subject_homepage = (By.CSS_SELECTOR, ".nebula-product-bar__inline-start>div>div[class*='nebula-product-bar__page-title']")
    switchCourseButton = (By.CSS_SELECTOR, ".nebula-button__icon-container")
    sc_elementary_product_card = (By.CSS_SELECTOR, ".draggable-nebula-cards__list > li[class*='nebula-product-block-card--dsce'] > div > div> div>a[data-click-name='Science Elementary']")
    sc_elementary_icon = (By.CSS_SELECTOR, "li[class*='nebula-product-block-card--dsce'] > div >div a[data-click-name='Science Elementary']>div>svg[class*='nebula-product-block-card__icon']")
    sc_elementary_label = (By.CSS_SELECTOR, "li[class*='nebula-product-block-card--dsce'] > div >div a[data-click-name='Science Elementary']>div>svg[class*='nebula-product-block-card__logo']")
    sc_elementary_homepage_title = (By.CSS_SELECTOR, ".comet-row__inner>div[class*='supplementary-masthead__wrapper']>h2")
    sc_elementary_earth_science_tab = ( By.CSS_SELECTOR, "div[class='comet-tabs']>label:nth-of-type(1)>span")
    sc_elementary_life_science_tab = (By.CSS_SELECTOR, "div[class='comet-tabs']>label:nth-of-type(2)>span")
    sc_elementary_physical_science_tab = (By.CSS_SELECTOR, "div[class='comet-tabs']>label:nth-of-type(3)>span")
    sc_elementary_asset_list = (By.CSS_SELECTOR, "div[aria-hidden='false']>ul>li")
    scienceTB_product_card = (By.CSS_SELECTOR, ".draggable-nebula-cards__list > li[class *='nebula-product-block-card--detb'] > div >div a[data-click-name='Science Techbook']")
    scienceTB_icon = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--detb'] > div >div a[data-click-name='Science Techbook']>div>svg[class*='nebula-product-block-card__icon']")
    scienceTB_label = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--detb'] > div >div a[data-click-name='Science Techbook']>div>svg[class*='nebula-product-block-card__logo']")
    scienceTB_homepage_title = (By.CSS_SELECTOR, ".nebula-product-bar__page-title>span")
    table_of_contents_button = (By.CSS_SELECTOR, ".nebula-action-bar__buttons-container>ul[aria-label='Links and Resources'] button")
    toc_modal_header = (By.CSS_SELECTOR, ".nebula-modal__header-container--full-width>div>h2,.toc-modal__header[id='toc-modal-header']")
    toc_modal_unit1_header = (By.CSS_SELECTOR, "div[class*='toc-modal__sub-wrapper-theme--']:nth-child(1) .toc-modal__sub-unit:nth-child(2) .toc-modal__sub-unit-title")
    techbook_overview_tab = (By.CSS_SELECTOR, "a[data-title='Overview']")
    techbook_table_of_contents_tab = (By.CSS_SELECTOR, "a[data-title='Table of Contents']")
    stem_connect_product_card = (By.CSS_SELECTOR, ".draggable-nebula-cards__list > li[class *='nebula-product-block-card--stem'] > div >div a[data-click-name='STEM Connect']")
    stem_connect_icon = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--stem'] > div >div a[data-click-name='STEM Connect']>div>svg[class*='nebula-product-block-card__icon']")
    stem_connect_label = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--stem'] > div >div a[data-click-name='STEM Connect']>div>svg[class*='nebula-product-block-card__logo']")
    stem_connect_homepage_title = (By.CSS_SELECTOR, ".product-bar__stem-connect>div>div>a[title='STEM Connect']>p>span, .nebula-product-bar__inline-start div.nebula-product-bar__page-title")
    stem_connect_unit_cards_list = (By.CSS_SELECTOR, "ul[class='course-units__cards-list']>li")
    mathTB_product_card = (By.CSS_SELECTOR, ".draggable-nebula-cards__list > li[class *='nebula-product-block-card--demb'] > div >div a[data-click-name='Math Techbook']")
    mathTB_icon = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--demb'] > div >div a[data-click-name='Math Techbook']>div>svg[class*='nebula-product-block-card__icon']")
    mathTB_label = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--demb'] > div >div a[data-click-name='Math Techbook']>div>svg[class*='nebula-product-block-card__logo']")
    mathTB_homepage_title = (By.CSS_SELECTOR, ".nebula-product-bar__page-title>span")
    coding_product_card = (By.CSS_SELECTOR, ".draggable-nebula-cards__list > li[class *='nebula-product-block-card--coding'] > div >div a[data-click-name='Coding']")
    coding_icon = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--coding'] > div >div a[data-click-name='Coding']>div>svg[class*='nebula-product-block-card__icon']")
    coding_label = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--coding'] > div >div a[data-click-name='Coding']>div>svg[class*='nebula-product-block-card__logo']")
    coding_homepage_title = (By.CSS_SELECTOR, "a[data-click-name*='Coding']>span")
    coding_de_logo = (By.CSS_SELECTOR, "coding-product-bar>.comet-product-bar--global>coding-platform-links>a[data-click-name='Home Page']")
    social_studies_product_card = (By.CSS_SELECTOR, ".draggable-nebula-cards__list > li[class*='nebula-product-block-card--socs'] > div >div a[data-click-name='Social Studies Techbook']")
    social_studies_icon = (By.CSS_SELECTOR, "li[class*='nebula-product-block-card--socs'] > div >div a[data-click-name='Social Studies Techbook']>div>svg[class*='nebula-product-block-card__icon']")
    social_studies_label = (By.CSS_SELECTOR, "li[class*='nebula-product-block-card--socs'] > div >div a[data-click-name='Social Studies Techbook']>div>svg[class*='nebula-product-block-card__logo']")
    socialTB_homepage_title = (By.CSS_SELECTOR, ".nebula-product-bar__page-title>span")
    trophy_icon = (By.CSS_SELECTOR, ".long-assignment-card__due-in>svg[class*='assignment-due-in__icon--trophy']")
    tiles_explore = (By.CSS_SELECTOR, ".nebula-card-row>li>div>a[data-click-name='Explore']")
    tiles_search = (By.CSS_SELECTOR, ".nebula-card-row>li>div>a[data-click-name='Search']")
    tiles_studio = (By.CSS_SELECTOR, ".nebula-card-row>li>div>a[data-click-name='Studio']")
    tiles_subjects = (By.CSS_SELECTOR, ".nebula-card-row>li>div>a[data-click-name='Subjects']")
    tiles_my_content = (By.CSS_SELECTOR, ".nebula-card-row>li>div>a[data-click-name='My Content']")
    tools_tray_more_option = (By.CSS_SELECTOR, ".hidden-for-mobile .tools-tray-tool.tray-more button.tools-tray-tool-item")
    T4Subject_Text = (By.CSS_SELECTOR, ".channels-rows-container h2")
    unit_page_title = (By.CSS_SELECTOR, ".techbook__banner-layout>div>div>h1")
    unassign_button_for_assignment = (By.CSS_SELECTOR, "td.assignment-table__cell.assignment-table__actions .table-action-menu__action-unassign--all")
    unassign_confirm_button = (By.CSS_SELECTOR, "button.comet-button.comet-button--danger.comet-modal__button.comet-modal__button--confirm")
    user_first_name = (By.CSS_SELECTOR, ".student-homepage__welcome>div[class='student-homepage__welcome-left']>div>p:nth-child(2)")
    view_profile_text = (By.CSS_SELECTOR, "div.nebula-profile-panel__inner > ul > li:nth-child(1) > a>span")
    view_profile_button = (By.CSS_SELECTOR, "div.nebula-profile-panel__inner > ul > li:nth-child(1) > a")
    view_profile_homepage = (By.CSS_SELECTOR, ".nebula-product-bar__page-title")
    waffle_button = (By.CSS_SELECTOR, "button[aria-label='Open Global Nav']")
    waffle_menu_my_content_card = (By.CSS_SELECTOR, ".comet-dropdown-menu .dex-color-card--my-content .comet-card__title,.nebula-global-nav__section a[href*='my-content'], a[data-click-name='My Content'][data-click-type='Global Navigation']")
    my_content_button = (By.CSS_SELECTOR, ".comet-dropdown-menu .dex-color-card--my-content .comet-card__title,.nebula-global-nav__section a[href*='my-content']>div>h3")
    welcome_message = (By.CSS_SELECTOR, ".student-homepage__welcome>div[class='student-homepage__welcome-left']>div>p:nth-child(1)")
    welcome_page_continue_to_experience_button = (By.CSS_SELECTOR, ".interests__form-inner--button-container .welcome20__submit-button")
    welcome_page_grades_container = (By.CSS_SELECTOR, ".welcome20__container .interests-form--welcome20 .interests__grades-group")
    welcome_page_interest_stem = (By.CSS_SELECTOR, ".comet-button.toggle__button[for='interests[28]']")
    welcome_page_interest_stem_selected = (By.CSS_SELECTOR, ".comet-button.toggle__button.comet-button--checked[for='interests[28]']")
    welcome_page_job_title_teacher = (By.CSS_SELECTOR, ".comet-button.toggle__button[for*='Teacher']:not(.comet-button--checked)")
    welcome_page_next_button = (By.CSS_SELECTOR, ".nebula-button.welcome20__submit-button.onboarding-form-button")
    welcome_page_select_your_interests_button = (By.CSS_SELECTOR, ".welcome20__form-inner--button-container .welcome20__submit-button")
    welcome_page_subjects = lambda subject_id : (By.CSS_SELECTOR, ".comet-button.toggle__button[for='subjects[{}]']".format(subject_id))
    welcome_page_subject_selected = lambda subject_id : (By.CSS_SELECTOR, ".comet-button.toggle__button.comet-button--checked[for='subjects[{}]'] input".format(subject_id))
    xbutton = (By.CSS_SELECTOR, ".nebula-modal__x-button.nebula-button")
    your_courses_cards = (By.CSS_SELECTOR, ".techbook-orientation__courses-container .techbook-orientation__courses-heading>h2")
    favorites_asset_action_button = lambda index: (By.CSS_SELECTOR, "[data-index*='Result number: {}'] button[data-click-name='Add to Favorites'], [data-index*='Result number: {}'] button[data-click-name='Add to Favorites']".format(index, index))
    quiz_button = (By.CSS_SELECTOR, ".nebula-global-nav__section a[href*='https://engage'],a.nebula-global-nav__button[href*='https://engage']")
    live_ask_quiz = (By.CSS_SELECTOR, ".de-nebula-action-bar__actions-area button:nth-child(2)")
    myquizzes=(By.CSS_SELECTOR,".de-nebula-action-bar__quiz-name span")
    Search_My_Quizzestitle=(By.CSS_SELECTOR,"div[class*='text-center'] h3")
    createNew_button=(By.CSS_SELECTOR,".de-nebula-action-bar__actions-area button:nth-child(3)")
    modelpopuptitle = (By.CSS_SELECTOR, "h4[id='modal-title']")
    activity_input = (By.CSS_SELECTOR, "input[id='modalActivityNameInput']")
    launch_button = (By.CSS_SELECTOR, "div.modal-footer button[class='btn btn-primary']")
    model_popup_title = (By.CSS_SELECTOR, "h4#modalActivityLinksLabel")
    codecopy = (By.CSS_SELECTOR, "button[class='btn btn-icon-white border-primary']")
    close_button = (By.CSS_SELECTOR, "button[class='close'], .modal-content button[class='close']")
    header_title = (By.CSS_SELECTOR, "div.de-activity-question__description h5")
    finish_button = (By.CSS_SELECTOR, "button[class='btn btn-sm btn-primary'],button[class='btn btn-sm btn-primary'][type='button']")
    myquizzespage_delogo = (By.CSS_SELECTOR, 'div.de-nebula-product-bar__inline-start a span.navbar-brand__logo')
    save_closebutton = (By.CSS_SELECTOR, "div.de-nebula-action-bar__buttons a[class='btn btn-sm btn-primary']")
    join_live_activity_cancel_button=(By.CSS_SELECTOR,"button[class='nebula-button nebula-button--m nebula-button--square nebula-button--ghost'] span[class='nebula-button__text']")
    join_live_activity_join_button=(By.CSS_SELECTOR,"button[class='nebula-button nebula-button--m nebula-button--square nebula-button--fill']")
    validation_text=(By.CSS_SELECTOR,"div[class='nebula-form-helper nebula-form-helper--has-icon nebula-form-helper--error'] span[id*='helper-text__activity-code']")
    enter_activity_code_inputfield=(By.CSS_SELECTOR,".nebula-modal__content-container .nebula-field-group--label-top.join-activity-modal__content input.nebula-input,input[id='activityCode']")
    theme_tab =(By.CSS_SELECTOR,"li[class='sub-nav__item'] a[data-click-name='Theme']")
    keikiartist=(By.CSS_SELECTOR,"img[class='student-profile-page__keiki-artist']")
    pickupnexttheme=(By.CSS_SELECTOR,"div[class*='student-profile-page__panel-header--theme'] h5[class='student-profile-page__panel-header-text']")
    select_abackgroundtitle=(By.CSS_SELECTOR,"section[class*='student-profile-page__panel-section--theme'] h6[class='student-profile-page__sub-heading']")
    backgrounds_grid =(By.CSS_SELECTOR,"ul[class='student-profile-page__themes-list'] li")
    selected_background=(By.CSS_SELECTOR,"ul[class='student-profile-page__themes-list'] li button[class*= 'student-profile-page__theme-button--active']")
    checked_green_icon=(By.CSS_SELECTOR,"ul[class='student-profile-page__themes-list'] svg[class*='student-profile-page__selected-check']")
    thrid_theme=(By.CSS_SELECTOR,"ul[class='student-profile-page__themes-list'] li:nth-child(3)")
    default_theme = (By.CSS_SELECTOR, "ul[class='student-profile-page__themes-list'] li:nth-child(1)")
    student_homepage_theme=(By.CSS_SELECTOR,"div[class='student-homepage__masthead']")
    profilepanel_theme=(By.CSS_SELECTOR,"div[class='nebula-profile-panel__info']")
    interests_button=(By.CSS_SELECTOR,"li[class='sub-nav__item'] a[data-click-name='Interests']")
    keiki_global_image=(By.CSS_SELECTOR,"img[class='student-profile-page__keiki-with-globe']")
    whatisyourinterestsheading=(By.CSS_SELECTOR,"div[class*='student-profile-page__panel-header--interests'] h5[class='student-profile-page__panel-header-text']")
    pickanything=(By.CSS_SELECTOR,"section[class*='student-profile-page__panel-section--interests'] h6[class='student-profile-page__sub-heading']")
    interests_grid=(By.CSS_SELECTOR,"ul[class='student-profile-page__interests-list'] li")
    thumbnails=(By.CSS_SELECTOR,"div[class*='nebula-thumbnail__inner--thumbnail-loaded122']")
    interest_thumbnail=(By.CSS_SELECTOR,"div[class*='nebula-thumbnail__inner--thumbnail-loaded']")
    interest_label_name=(By.CSS_SELECTOR,"div[class='student-profile-page__interest-button-title'] span")
    animalsinterest=(By.CSS_SELECTOR,"ul[class='student-profile-page__interests-list'] li button[aria-label='Animals']")
    selected_interest=(By.CSS_SELECTOR,"button[class='student-profile-page__interest-button student-profile-page__interest-button--active']")
    selectedinterests_button=(By.CSS_SELECTOR,"a[class='nebula-button nebula-button--s nebula-button--pill nebula-button--fill nebula-button--icon-left do-push-state']")
    checked_icon=(By.CSS_SELECTOR,"button[class='student-profile-page__interest-button student-profile-page__interest-button--active'] svg[class*='student-profile-page__selected-check']")
    keikireader_image=(By.CSS_SELECTOR,"section[class='student-profile-page__panel-section student-profile-page__panel-section--avatar'] img[class='student-profile-page__keiki-reading']")
    pickupavatar_text=(By.CSS_SELECTOR,"section[class='student-profile-page__panel-section student-profile-page__panel-section--avatar'] h5[class='student-profile-page__panel-header-text']")
    selected_avatar  =(By.CSS_SELECTOR,"ul[class='student-profile-page__avatar-category'] li[class='student-profile-page__avatar-option student-profile-page__avatar-option--selected']")
    selected_homepage_avatar=(By.CSS_SELECTOR," div[class='student-homepage__welcome-left'] a[class='student-homepage__profile-link'] div[aria-label='walking robot'], div[class='student-homepage__welcome-left'] a[class='student-homepage__profile-link'] div[class*='student-homepage__avatar']")
    first_avatar=(By.CSS_SELECTOR,"ul[class='student-profile-page__avatar-category'] li button[aria-label='walking robot'], ul[class='student-profile-page__avatar-category'] li:nth-child(1) button[class='avatar-image']")
    avatar_checked_icon=(By.CSS_SELECTOR,"li[class='student-profile-page__avatar-option student-profile-page__avatar-option--selected'] svg[class*='student-profile-page__selected-check']")
    min_avatar=(By.CSS_SELECTOR,"button[aria-label='Open Profile Panel'] img")
    default_avatar = (By.CSS_SELECTOR, "ul[class='student-profile-page__avatar-category'] li button[aria-label='generic silhouette'], ul[class='student-profile-page__avatar-category'] li:nth-child(41) button[class='avatar-image']")
    sciencetb_tab = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--DETB'] button")
    mathtb_tab = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--DEMB'] button")
    mathtb_tab_icon = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--DEMB']>button>div>svg:nth-child(1)>use, #math")
    mathtb_tab_name = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--DEMB']>button>div>svg:nth-child(2)>use, #math-techbook-logo")
    socialstudies_tab = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--SOCS']>button")
    socialstudies_icon = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--SOCS']>button>div>svg:nth-child(1)>use, #social-studies")
    socialstudies_name = (By.CSS_SELECTOR, "ul[class='techbook-entry__header'] li[class*='techbook-entry__header-item--SOCS']>button>div>svg:nth-child(2)>use, #social-studies-techbook-logo")
    activites_button_sciencetb=(By.CSS_SELECTOR, ".techbook-entry__panel--DETB button[data-click-name='Activities']")
    activites_button_mathtb = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB button[data-click-name='Activities']")
    activites_button_socialtb = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS button[data-click-name='Activities']")
    about_button=(By.CSS_SELECTOR, ".techbook-entry__panel--DETB button[data-click-name='About'] span")
    about_button_mathtb = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB button[data-click-name='About'] span")
    about_button_socialtb = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS button[data-click-name='About'] span")
    glossary_button=(By.CSS_SELECTOR,".techbook-entry__panel--DETB a[data-click-name='Glossary'] span")
    glossary_button_mathtb = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB a[data-click-name='Glossary'] span")
    glossary_button_socialtb = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS a[data-click-name='Glossary'] span")
    mathtb_glossarybutton=(By.CSS_SELECTOR,"a[href*='DEMB'] span[class='nebula-button__text']")
    socialstudies_glossarybutton=(By.CSS_SELECTOR,"a[href*='SOCS'] span[class='nebula-button__text']")
    quickcode_button=(By.CSS_SELECTOR, ".techbook-entry__panel--DETB button[data-click-name='Quick Code'] span")
    quickcode_button_mathtb = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB button[data-click-name='Quick Code'] span")
    quickcode_button_socialtb = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS button[data-click-name='Quick Code'] span")
    stemconnect_product=(By.CSS_SELECTOR,"li.nebula-product-block-card--stem div.nebula-card__content a[data-click-name='STEM Connect']")
    science_middle_product=(By.CSS_SELECTOR,"li.nebula-product-block-card--dsc div.nebula-card__content a[data-click-name='Science Middle School']")
    science_middle_icon = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--dsc'] > div >div a[data-click-name='Science Middle School']>div>svg[class*='nebula-product-block-card__icon']")
    science_middle_label = (By.CSS_SELECTOR, "li[class *='nebula-product-block-card--dsc'] > div >div a[data-click-name='Science Middle School']>div>svg[class*='nebula-product-block-card__logo']")
    course_card=(By.CSS_SELECTOR,"div.techbook-entry__panel--DETB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--course']")
    course_card_math_TB = (By.CSS_SELECTOR, "div.techbook-entry__panel--DEMB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--course']")
    course_card_social_TB = (By.CSS_SELECTOR, "div.techbook-entry__panel--SOCS div.techbook-entry__activity-wrapper a[class*='techbook-course-card--course']")
    course_card_title_sciencetb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DETB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--course']>div[class='techbook-course-card__header']")
    course_card_title_mathtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DEMB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--course']>div[class='techbook-course-card__header']")
    course_card_title_socialtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--SOCS div.techbook-entry__activity-wrapper a[class*='techbook-course-card--course']>div[class='techbook-course-card__header']")
    jump_back_in_card=(By.CSS_SELECTOR,"div.techbook-entry__panel--DETB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--resume']")
    jump_back_in_card_mathtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DEMB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--resume']")
    jump_back_in_card_socialtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--SOCS div.techbook-entry__activity-wrapper a[class*='techbook-course-card--resume']")
    jump_back_in_card_title_sciencetb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DETB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--resume']>div[class='techbook-course-card__header']")
    jump_back_in_card_title_mathtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DEMB div.techbook-entry__activity-wrapper a[class*='techbook-course-card--resume']>div[class='techbook-course-card__header']")
    jump_back_in_card_title_socialtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--SOCS div.techbook-entry__activity-wrapper a[class*='techbook-course-card--resume']>div[class='techbook-course-card__header']")
    nextassignments_card_title_sciencetb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DETB div.techbook-entry__activity-wrapper [aria-label='Next Assignment:']>div[class='techbook-course-card__header']")
    nextassignments_card_title_mathtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DEMB div.techbook-entry__activity-wrapper [aria-label='Next Assignment:']>div[class='techbook-course-card__header']")
    nextassignments_card_title_socialtb = (By.CSS_SELECTOR,"div.techbook-entry__panel--SOCS div.techbook-entry__activity-wrapper [aria-label='Next Assignment:']>div[class='techbook-course-card__header']")
    nextassignments_card_sciencetb=(By.CSS_SELECTOR,"div.techbook-entry__panel--DETB div.techbook-entry__activity-wrapper [aria-label='Next Assignment:']")
    nextassignments_card_mathtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--DEMB div.techbook-entry__activity-wrapper [aria-label='Next Assignment:']")
    nextassignments_card_socialtb = (By.CSS_SELECTOR, "div.techbook-entry__panel--SOCS div.techbook-entry__activity-wrapper [aria-label='Next Assignment:']")
    glossary_content=(By.CSS_SELECTOR,"div.glossary-list-region ul[class='glossary-terms-list comet-list-group__list'] li")
    getstartedtext_sciencetbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DETB']  p.techbook-entry__panel-title")
    coursebropdown_sciencetbtab = (By.CSS_SELECTOR, "div.techbook-entry__panels div[class*='techbook-entry__panel--DETB']  select option")
    gobutton_sciencetbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DETB']  button[data-click-name='Go']")
    thumbnail_sciencetbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DETB']  div[class*='techbook-entry__panel-textpanel-end--intro']")
    description_sciencetbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DETB']  p.techbook-entry__panel-description:nth-child(2)")
    getstartedtext_mathtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DEMB']  p.techbook-entry__panel-title")
    coursebropdown_mathbtab = (By.CSS_SELECTOR, "div.techbook-entry__panels div[class*='techbook-entry__panel--DEMB']  select option")
    gobutton_mathtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DEMB']  button[data-click-name='Go']")
    thumbnail_mathtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DEMB']  div[class*='techbook-entry__panel-textpanel-end--intro']")
    description_mathtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--DEMB']  p.techbook-entry__panel-description:nth-child(2)")
    getstartedtext_socialtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--SOCS']  p.techbook-entry__panel-title")
    coursebropdown_socialtbtab = (By.CSS_SELECTOR, "div.techbook-entry__panels div[class*='techbook-entry__panel--SOCS']  select option")
    gobutton_socialtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--SOCS']  button[data-click-name='Go']")
    thumbnail_socialtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--SOCS']  div[class*='techbook-entry__panel-textpanel-end--intro']")
    description_socialtbtab = (By.CSS_SELECTOR,"div.techbook-entry__panels div[class*='techbook-entry__panel--SOCS']  p.techbook-entry__panel-description:nth-child(2)")
    selected_about_button = (By.CSS_SELECTOR, ".techbook-entry__panel--DETB button[data-click-name='About'][active='true'] span")
    selected_about_button_mathtb = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB button[data-click-name='About'][active='true'] span")
    selected_about_button_socialtb = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS button[data-click-name='About'][active='true'] span")
    selected_activites_button_sciencetb = (By.CSS_SELECTOR, ".techbook-entry__panel--DETB button[data-click-name='Activities'][active='true']")
    selected_activites_button_mathtb = (By.CSS_SELECTOR, ".techbook-entry__panel--DEMB button[data-click-name='Activities'][active='true']")
    selected_activites_button_socialtb = (By.CSS_SELECTOR, ".techbook-entry__panel--SOCS button[data-click-name='Activities'][active='true']")
    about_heading = (By.CSS_SELECTOR, "div[class*='techbook-entry__panel-textpanel-start techbook-entry__panel-textpanel-start--about'] p.techbook-entry__panel-title")
    about_description = (By.CSS_SELECTOR,"div[class*='techbook-entry__panel-textpanel-start techbook-entry__panel-textpanel-start--about'] p.techbook-entry__panel-description")
    about_image = (By.CSS_SELECTOR, "div[class*='techbook-entry__panel-textpanel-end techbook-entry__panel-textpanel-end--about']")
    mathtb_about_heading = (By.CSS_SELECTOR, "div[class='techbook-entry__panel techbook-entry__panel--DEMB'] p.techbook-entry__panel-title")
    mathtb_about_description = (By.CSS_SELECTOR,"div[class='techbook-entry__panel techbook-entry__panel--DEMB'] p.techbook-entry__panel-description")
    mathtb_about_image = (By.CSS_SELECTOR,"div[class='techbook-entry__panel techbook-entry__panel--DEMB'] div[class*='techbook-entry__panel-textpanel-end techbook-entry__panel-textpanel-end--about']")
    socialtb_about_heading = (By.CSS_SELECTOR, "div[class='techbook-entry__panel techbook-entry__panel--SOCS'] p.techbook-entry__panel-title")
    socialtb_about_description = (By.CSS_SELECTOR,"div[class='techbook-entry__panel techbook-entry__panel--SOCS'] p.techbook-entry__panel-description")
    socialtb_about_image = (By.CSS_SELECTOR,"div[class='techbook-entry__panel techbook-entry__panel--SOCS'] div[class*='techbook-entry__panel-textpanel-end techbook-entry__panel-textpanel-end--about']")
    explore_tab_banner_heading=(By.CSS_SELECTOR,"h3.nebula-banner__headline")
    asset_heading=(By.CSS_SELECTOR,"h1.asset-detail-page-header__headline")
    asset_player=(By.CSS_SELECTOR,"div[class='video-player__thumbnail-image-container']")
    banner=(By.CSS_SELECTOR,"div[class='explore-page'] div[class='explore-page__student-banner']")
    globalnavflyout = (By.CSS_SELECTOR, "nav[id='nebula-global-nav'], nav.nebula-icon-sidebar-global--expanded")
    sectionsheadinginglobalnavmenu = (By.CSS_SELECTOR, "section[class='nebula-global-nav__section'] h2[class='nebula-global-nav__header'], .nebula-icon-sidebar-global__section h2")
    globalnavmenuclose_button = (By.CSS_SELECTOR, "nav[class='nebula-global-nav']  button, button[aria-label='Close Global Nav']")
    globalnavmenuoptions=lambda index:(By.CSS_SELECTOR,"section:nth-child({}) a h3".format(index))
    globalNav_DELogo=(By.CSS_SELECTOR,".nebula-product-bar a[aria-label='Home'][data-click-type='Global Navigation']")
    explore_option = (By.CSS_SELECTOR, "a[data-click-name='Explore'] h3")
    browseStandards_option = (By.CSS_SELECTOR, "nav.nebula-global-nav section:nth-child(3) a[data-click-name='Browse Standards'] h3")
    educatorSupports_option = (By.CSS_SELECTOR, "nav.nebula-global-nav section:nth-child(3) a[data-click-name='Educator Supports'] h3")
    stateacademicStandards_option = (By.CSS_SELECTOR, "a[data-click-name='State & Academic Standards'] h3")
    quiz_option = (By.CSS_SELECTOR, "a[data-click-name='Quiz'] h3")
    pathway_option = (By.CSS_SELECTOR, "nav.nebula-global-nav section:nth-child(5)  a[data-click-name='Pathway'] h3")
    user_profile_button = (By.CSS_SELECTOR, ".user-menu__button,button[aria-label='Open Profile Panel']")
    page_upload_file_percentage = (By.CSS_SELECTOR, "td[data-label='Status'], td[data-label='STATUS']")
    asset_video_thumbnail_by_index_and_guid_board = lambda guid: (By.CSS_SELECTOR, ".video-player__thumbnail .video-player__thumbnail-image[style*='thumbnails/{}']".format(guid))
    espresso_favorites = (By.CSS_SELECTOR, ".user-menu__button,button[aria-label='Open Favorites']")
    create_with_studio_modal = (By.CSS_SELECTOR,".nebula-modal__header-container")
    take_survey_pop_up = (By.CSS_SELECTOR, ".component-row__content  .nebula-modal__container button[aria-label='close modal']")
    ask_live_quiz_modal_title = (By.CSS_SELECTOR, ".d-inline-block.mb-0")
    allow_guest_slider = (By.CSS_SELECTOR, ".de-toggle-switch")
    allow_guest_slider_color = (By.CSS_SELECTOR, ".de-toggle-switch input[id='ask-live-guest-access']+span")
    launch_button_disabled_ask_live_quiz = (By.CSS_SELECTOR, ".modal-footer button.disabled#step4")
    school_tab_sso = (By.CSS_SELECTOR, "a[href='/sites']")
    school_search_box = (By.CSS_SELECTOR, ".comet-form__label[for='school']+[id='school']")
    school_search_button = (By.CSS_SELECTOR, ".admin-form__button-container button[form='admin-form--browse-schools']")
    school_link_search_results = lambda schoolName: (By.CSS_SELECTOR, ".comet-data-table__row .comet-data-table__cell[title='{}'] a".format(schoolName))
    school_name_breadcrumb = (By.CSS_SELECTOR, ".admin-breadcrumb .admin-breadcrumb__span")
    manage_menu_settings_dropdown = (By.CSS_SELECTOR, ".manage-menu button[data-comet-popover='manage-school-menu']")
    school_setting_link = (By.CSS_SELECTOR, ".comet-list-group__row a[href*='/sites'][href*='/product-settings']")
    product_setting_header = (By.CSS_SELECTOR, ".admin-row__header h3")
    all_product_settings = (By.CSS_SELECTOR, ".admin-form--edit-product-settings")
    show_spiral_setting_No = (By.CSS_SELECTOR, ".comet-form__radio-button[for*='showspiralquickfire'] input[id*='no']")
    default_setting_No = (By.CSS_SELECTOR, "#showsearchstudioboards-setting-level")
    show_spiral_setting_No_checked = (By.CSS_SELECTOR, "input[id='showspiralquickfire-no'][checked]")
    show_spiral_setting_Yes = (By.CSS_SELECTOR, "input[id='showspiralquickfire-yes']")
    show_spiral_setting_Yes_checked = (By.CSS_SELECTOR, "input[id='showspiralquickfire-yes'][checked]")
    show_engage_quiz_library_setting_No = (By.CSS_SELECTOR, ".comet-form__radio-button[for*='showengagequizlibrary'] input[id*='no']")
    show_engage_quiz_library_setting_Yes = (By.CSS_SELECTOR, ".comet-form__radio-button[for*='showengagequizlibrary'] input[id*='yes']")
    ask_live_cancel_button = (By.CSS_SELECTOR, "#ask-live-back")
    product_setting_Save_button = (By.CSS_SELECTOR, ".admin-form__button-container button[type='submit']")
    want_to_edit_this_lesson_popup = (By.CSS_SELECTOR, "#pendo-guide-container")
    want_to_edit_this_lesson_close_button_popup = (By.CSS_SELECTOR, "#pendo-guide-container button._pendo-close-guide")
    waffle_menu_state_Academic_standard = (By.CSS_SELECTOR,".nebula-global-nav__section a[href*='standards-alignments']")
    assessment_question_dropdown_text = (By.CSS_SELECTOR, ".btn-question-dropdown .comet-button__text span:nth-child(2)")
    assign_modal_popup = (By.CSS_SELECTOR, "iframe[src*='/assign/']")
    studio_player_title = (By.CSS_SELECTOR, ".studio-player-action-bar__title")
    studio_player_page_content = (By.CSS_SELECTOR, ".studio-player-page__content-container")
    studio_player_title_student = (By.CSS_SELECTOR, ".student-view-action-bar__title")
    studio_player_page_content_student = (By.CSS_SELECTOR, ".editor__zoom-content")
    techbook_mini_card_title = (By.CSS_SELECTOR, ".techbook__minicards .techbook-mini-card a.nebula-card__title")
    total_science_course_grade_card = (By.CSS_SELECTOR, ".nebula-card__content a[href*='/learn/techbook/courses/'].nebula-card__title")
    science_course_grade_card = lambda index: (By.CSS_SELECTOR, ".techbook__minicards li.techbook-mini-card__container:nth-child({}) a[href*='/learn/techbook/courses/'].nebula-card__title".format(index))
    techbook_for_grades = (By.CSS_SELECTOR, ".techbook-landing__main-content--secondary .pinnable-cards__main-content-heading h3")
    my_de_header = (By.CSS_SELECTOR, "h2.nebula-icon-sidebar-global__section-header--my-de")
    global_nav_waffle_menu = (By.CSS_SELECTOR, "button[aria-controls='nebula-global-nav']")
    de_consent_banner_cookies_button = (By.CSS_SELECTOR, "#de-consent-accept-cookies")

class MyContentLocators:
    asset_delete_button = (By.CSS_SELECTOR, ".comet-dropdown-menu.visible .comet-list-group__row:nth-child(6) button, .nebula-dropdown__content .nebula-dropdown__item:nth-child(4) button")
    asset_move_to_trash_confirm = (By.CSS_SELECTOR, ".nebula-modal__container .nebula-button--fill")
    cancel_button = (By.CSS_SELECTOR, ".nebula-modal__container .nebula-modal__actions-container button:nth-child(1),.nebula-modal__actions-container .nebula-button--square.nebula-button--ghost, .comet-modal__button--cancel")
    choose_button = (By.CSS_SELECTOR, ".my-content-modal .comet-modal__button:not(.comet-modal__button--cancel),.nebula-modal__actions-container .nebula-button--fill")
    district_content_tab = (By.CSS_SELECTOR, ".nebula-action-bar__tabs .nebula-tabs__container .nebula-tabs__list-item a[href*='my-content/account']")
    district_content_tab_selected = (By.CSS_SELECTOR, ".nebula-action-bar__tabs .nebula-tabs__container .nebula-tabs__list-item a[href*='my-content/account'].router-link-active")
    empty_folder = (By.CSS_SELECTOR, "div>p[class*='empty-state__paragraph']")
    loading_spinner_icon = (By.CSS_SELECTOR, ".comet-spinner__icon")
    my_content_add_button = (By.CSS_SELECTOR,".comet-modal__footer .comet-button:not(.comet-modal__button--cancel),.nebula-modal__actions-container .nebula-button--square.nebula-button--fill")
    my_content_folder_area = (By.CSS_SELECTOR, ".modal-container .my-content__folder,.nebula-modal__inner .my-content-modal__tabs-container")
    my_content_modal_assets = (By.CSS_SELECTOR, "div[class='folder__browse browse-items']>div>div>div>label>span")
    my_content_modal_assets_by_index = lambda index: (By.CSS_SELECTOR,"div[class='folder__browse browse-items']>div:nth-child({})>div>div>label>span".format(index))
    my_content_modal_assets_by_index_selected = lambda index: (By.CSS_SELECTOR,".nebula-modal__inner .my-content__browse .folder__browse div:nth-child({})[role='listitem'] .folder__selectable.folder__selectable--selected".format(index))
    my_content_modal_header = (By.CSS_SELECTOR, ".my-content-modal .modal__heading")
    my_content_modal_tab_by_index = lambda index: (By.CSS_SELECTOR, "div.nebula-modal__content-container .nebula-tabs__list-item:nth-child({}) button".format(index))
    my_content_modal_tab_selected_by_index = lambda index: (By.CSS_SELECTOR,"div.nebula-modal__content-container .nebula-tabs__list-item.nebula-tabs__list-item--selected:nth-child({}) button".format(index))
    my_content_modal_tab_button = (By.CSS_SELECTOR, "div[class='my-content__actions'] > button")
    my_content_page_actions_button = (By.CSS_SELECTOR, ".nebula-table__row .nebula-table__cell[data-label='Actions'] button.nebula-button")
    my_content_page_actions_button_by_index = lambda index: (By.CSS_SELECTOR, ".nebula-table__row:nth-child({}) .nebula-table__cell[data-label='Actions'] button.nebula-button".format(index))
    my_content_page_actions_button_open_by_index = lambda index: (By.CSS_SELECTOR, ".nebula-table__row:nth-child({}) .nebula-table__cell[data-label='Actions'] button.nebula-button[aria-expanded='true']".format(index))
    my_content_page_actions_button_text_by_index = lambda index: (By.CSS_SELECTOR, ".comet-data-table__row:nth-child({}) .comet-data-table__cell[data-label='Actions'] button#asset-1-dropdown span[class='comet-button__text']".format(index))
    my_content_page_asset = lambda asset_guid: (By.CSS_SELECTOR, "tbody .nebula-table__row .nebula-table__cell a[href*='{}']".format(asset_guid))
    my_content_show_more_button = (By.CSS_SELECTOR, ".component-card-list.component-lesson-row__items .nebula-button--fill")
    my_content_page_header = (By.CSS_SELECTOR, ".my-content__header")
    my_content_page_star_icon = (By.CSS_SELECTOR, "div#mycontent-tabs span.icon-star")
    my_content_tab = (By.CSS_SELECTOR, ".my-content__row--squish:nth-child(2) .my-content__tab a[href*='my-content/user'], .nebula-action-bar__tabs nav[aria-label='tab navigation'] ul li a[href*='/suite/my-content/user']")
    my_content_tab_selected = (By.CSS_SELECTOR, ".my-content__row--squish:nth-child(2) .my-content__tab.comet-tab__label--selected a[href*='my-content/user'],  .nebula-action-bar__tabs nav[aria-label='tab navigation'] ul li.nebula-tabs__list-item--selected a[href*='/suite/my-content/user']")
    my_uploads_tab = (By.CSS_SELECTOR, ".my-content__row--squish:nth-child(3) .my-content__tabs .my-content__tab:nth-child(2) ,.my-content__tool-bar-group .my-content__tabs ul li:nth-child(2) a")
    school_content_tab = (By.CSS_SELECTOR, ".nebula-action-bar__tabs .nebula-tabs__container .nebula-tabs__list-item a[href*='my-content/site']")
    school_content_tab_selected = (By.CSS_SELECTOR, ".nebula-action-bar__tabs .nebula-tabs__container .nebula-tabs__list-item a[href*='my-content/site'].router-link-active")
    trash_button = (By.CSS_SELECTOR, ".my-content__row--squish:nth-child(3) .my-content__tabs .my-content__tab:nth-child(3), .my-content__tool-bar-group .my-content__tabs ul li:nth-child(4) a")

class UnitPageLocators:
    breadcrumb_dropdown_option_by_guid = lambda option_guid: (By.CSS_SELECTOR, "li[class='nebula-list-item']>a[href*='{}']>span".format(option_guid))
    explore_concepts_header = (By.CSS_SELECTOR, ".unit-panel__content .unit-heading-3")
    explore_option = (By.CSS_SELECTOR, "section:nth-child(3) > a[href*='explore'] h3")
    explore_letsgo_button = (By.CSS_SELECTOR, "div[class='nebula-banner__buttons']>a>span[class='nebula-button__text'],div[class='nebula-banner__buttons']>button>span[class='nebula-button__text']")

class PlayerPageLocators:
    player_page_container = (By.CSS_SELECTOR, "#player-app")
    player_page_main_header = (By.CSS_SELECTOR, "#player-app h1")
    player_page_sub_header = (By.CSS_SELECTOR, "div[class='comet-masthead'] div[class='comet-masthead__copy'] span[class='comet-masthead__type']")
    player_page_asset_section = (By.CSS_SELECTOR, ".asset-detail-page__player-container")

class AssignmentLocators:
    open_assignment_button = (By.CSS_SELECTOR, ".assignment-instructions-modal__button-row .assignment-instructions-modal__button:nth-child(2),.assignment-modal__button--open.nebula-button--fill")
    assignment_ellipses_button = (By.CSS_SELECTOR, ".assignment-actions-menu .learn-nebula-card-actions__button,.nebula-table>tbody>tr>td[class='nebula-table__cell']>div[class*='nebula-dropdown']>button")
    assignment_ellipses_button_by_index = lambda index: (By.CSS_SELECTOR, ".nebula-table>tbody>tr:nth-child({})>td[class='nebula-table__cell']>div[class*='nebula-dropdown']>button".format(index))
    assignment_ellipses_view_details_option_by_index = lambda index: (By.CSS_SELECTOR, "table tbody tr:nth-child({}) td[class*='nebula-table__cell']>div[class*='nebula-dropdown']>button".format(index))
    assignment_ellipses_unassign_option_by_index = lambda index: (By.CSS_SELECTOR, "tbody>tr:nth-child({})>td>div[class*='nebula-dropdown']>ul>div>div:nth-child(4)>li>button".format(index))
    assignment_nextbutton = (By.CSS_SELECTOR, ".assign-page__action-button.nebula-button--square.nebula-button--fill")
    assignment_classone_checkbox_new = (By.CSS_SELECTOR, ".assign-step__classrooms-container .assign-step__classroom:nth-child(1) .nebula-checkbox__visual")
    assignment_assignstartdate = (By.CSS_SELECTOR,".assign-step__date-picker-container div.nebula-datepicker input#assign-start-date")
    assignment_select_date_button = (By.CSS_SELECTOR, ".action-row .nebula-button:nth-child(2)")
    assignment_select_start_date = (By.CSS_SELECTOR, ".nebula-label[for='assign-start-date']+div .picker-cells button[class*='open selected today'],.nebula-label[for='assign-start-date']+div .dp__calendar div[class*='dp__today']")
    assignment_select_due_date = (By.CSS_SELECTOR, ".nebula-label[for='assign-due-date']+div .picker-cells button[class*='open today'] + button")
    assignment_select_due_date_Today = (By.CSS_SELECTOR, ".nebula-label[for='assign-due-date']+div .dp__calendar div[class*='dp__today']")
    assignment_due_date_disabled = (By.CSS_SELECTOR, ".nebula-label[for='assign-due-date']+div .picker-cells button[class*='open today'] + button[disabled='disabled']")
    assignment_due_index_disabled = lambda index: (By.CSS_SELECTOR,".nebula-label[for='assign-due-date']+div .picker-cells button[data-id='{}'][disabled='disabled']".format(index))
    assignment_due_index = lambda index: (By.CSS_SELECTOR,".nebula-label[for='assign-due-date']+div .picker-cells button[data-id='{}']".format(index))
    assignment_calender_due_next_button = (By.CSS_SELECTOR, ".dp--arrow-btn-nav[aria-label='Next month']")
    assignment_calender_All_due_dates = (By.CSS_SELECTOR, ".nebula-label[for='assign-due-date']~.nebula-field-group__element-container .dp__pointer:not(.dp__cell_offset)")
    assignment_calender_due_month = (By.CSS_SELECTOR, ".dp__month_year_wrap button.dp__btn.dp__month_year_select:nth-child(1)")
    assignment_calender_due_year = (By.CSS_SELECTOR, ".dp__month_year_wrap button.dp__btn.dp__month_year_select:nth-child(2)")
    assignment_assignduedate = (By.CSS_SELECTOR, ".assign-step__date-picker-container div.nebula-datepicker input#assign-due-date")
    assignment_assignbutton_new = (By.CSS_SELECTOR, ".assign-page__assign-container button.assign-page__action-button--assign")
    assignment_page_previous_button = (By.CSS_SELECTOR, ".assign-page__action-button.nebula-button--square.nebula-button--ghost")
    assignment_viewassignmentmanager = (By.CSS_SELECTOR, ".assign-page__button-container a:nth-child(1)")
    assignment_confirmationheader = (By.CSS_SELECTOR, ".assign-step.assign-step--four div.assign-step__heading-container  p")
    due_date_text_in_success_msg = (By.CSS_SELECTOR, ".assign-step__group.assign-step__group--info .assign-step__dates p:nth-child(2)")
    cancel_button_unassign_modal = (By.CSS_SELECTOR, "form#unassign-all button.comet-modal__button--cancel.js-comet-modal__close-button, .nebula-modal__container>div>div[class*='nebula-modal__actions-container']>div>button[class*='nebula-button--flat']")
    student_assignment_by_index = lambda index: (By.CSS_SELECTOR, ".assignments-grid__assignments:nth-child({}) a".format(index))
    student_assignment_class_name_by_index = lambda index: (By.CSS_SELECTOR, ".students-assignments-table tbody .students-assignment-table__row:nth-child({}) .students-assignment-table__class,.long-assignment-card__assignment-classroom".format(index))
    student_assignment_completed_date_by_index = lambda index: (By.CSS_SELECTOR, ".students-assignments-table tbody .students-assignment-table__row:nth-child({}) .completed-date,.long-assignment-card__title".format(index))
    student_assignment_due_date_by_index = lambda index: (By.CSS_SELECTOR, "div[class='assignments-grid__assignments']>ul>li:nth-child({})>div>a>div:nth-child(2)>div>span:nth-child(2)>span:nth-child(2)".format(index))
    student_assignment_name_by_index = lambda index: (By.CSS_SELECTOR, ".students-assignments-table tbody .students-assignment-table__row:nth-child({}) .students-assignment-table__assignment-name,.long-assignment-card__title".format(index))
    student_first_assignment = (By.CSS_SELECTOR, ".assignments-grid__assignments a")
    student_assignment_page_tab_by_index = lambda index: (By.CSS_SELECTOR, ".student-assignments__toolbar .student-assignment__toggle:nth-child({})".format(index))
    student_assignment_done = (By.CSS_SELECTOR, ".assignments-dashboard__card-group:nth-child(2) a[aria-label*='assignments done']")
    student_assignment_listview_button = (By.CSS_SELECTOR, ".assignments-grid__display-toggle--desktop button[aria-label='Display assignments as list.']")
    student_assignment_listview = (By.CSS_SELECTOR, ".assignments-grid__assignment--list")
    student_assignment_page_tab_by_index_selected = lambda index: (By.CSS_SELECTOR, ".student-assignments__toolbar .student-assignment__toggle.student-assignment__toggle--active:nth-child({}),.sub-nav__item a[href*='/students/assignments']".format(index))
    student_assignment_score_by_index = lambda index: (By.CSS_SELECTOR, ".students-assignments-table tbody .students-assignment-table__row:nth-child({}) .students-assignment-table__score".format(index))
    student_assignment_status_by_index = lambda index: (By.CSS_SELECTOR, ".assignments-grid__assignment--list:nth-child({}) .assignment-status-badge".format(index))
    student_assignment_teacher_by_index = lambda index: (By.CSS_SELECTOR, ".students-assignments-table tbody .students-assignment-table__row:nth-child({}) .students-assignment-table__teacher,.long-assignment-card__assignment-teacher".format(index))
    student_assignment_type_by_index = lambda index: (By.CSS_SELECTOR, ".students-assignments-table tbody .students-assignment-table__row:nth-child({}) .students-assignment-table__type,.long-assignment-card__title".format(index))
    student_assignment_tab = (By.CSS_SELECTOR,"#students-app .students-tabs .students-tabs__label a[href='/learn/students/assignments'],a[href='/learn/students/assignments'][data-click-name='Assignments']")
    student_assignment_tab_selected = (By.CSS_SELECTOR,"#students-app .students-tabs .students-tab__label--selected a[href='/learn/students/assignments'],a[href='/learn/students/assignments']")
    unassign_button_unassign_modal = (By.CSS_SELECTOR, "form#unassign-all button.comet-modal__button.comet-modal__button--confirm, .nebula-modal__container>div>div[class*='nebula-modal__actions-container']>div>button[id='unassign-assignment']")
    assignment_complete_button=(By.CSS_SELECTOR,".asset-detail-page__assignment .nebula-button--fill,.asset-detail-page__action-button.nebula-button--square.nebula-button--fill")
    assignmentpage_details_button=(By.CSS_SELECTOR,"button[aria-label='Details']")
    details_popup_modelassigndate=(By.CSS_SELECTOR,"span[class='assignment-details-modal__assignment-creation-date']")
    details_popup_modelassignduedate = (By.CSS_SELECTOR, "span[class='assignment-details-modal__assignment-due-date']")
    details_popup_modelteacher=(By.CSS_SELECTOR,"span[class='assignment-details-modal__assignment-teacher']")
    details_popup_modelclassroom = (By.CSS_SELECTOR, "span[class='assignment-details-modal__assignment-classroom']")
    details_popup_model_status=(By.CSS_SELECTOR,"div[class*='nebula-badge nebula-badge--light-gray']")
    details_popup_model_heading=(By.CSS_SELECTOR,"assignment-details-modal__title")
    details_popup_model_cancelbutton=(By.CSS_SELECTOR,"button[class*='assignment-details-modal__button--close']")
    first_assignment_name = (By.CSS_SELECTOR, ".nebula-table__row:nth-child(1) .assignment-link-list__title-container a[href*='/learn/assignments']")
    first_assignment_name_student = lambda name: (By.CSS_SELECTOR, ".assignments-grid__assignment--list a[aria-label*='{}'] .long-assignment-card__title".format(name))